### ISSUE TITLE
CSI Driver probe failed (reading 'datasetParentName')

### ISSUE THREAD

**Issue by teknofile** [democratic-csi/democratic-csi#205]
I've been trying to configure the CSI driver to allow for NFS/ISCSI provisioning. Currently I am starting with NFS. The "Cannot read properties" error i'm not sure what it is reffering to, the value in the helm values I am providing or a configuration issue with in TrueNAS?

```
(~) -> kubectl -n democratic-csi logs zfs-nfs-democratic-csi-controller-b6577df75-cbgmh external-provisioner 
I0610 17:53:26.177975       1 feature_gate.go:245] feature gates: &{map[]}
I0610 17:53:26.178195       1 csi-provisioner.go:139] Version: v3.1.0
I0610 17:53:26.178225       1 csi-provisioner.go:162] Building kube configs for running in cluster...
I0610 17:53:26.180592       1 connection.go:154] Connecting to unix:///csi-data/csi.sock
I0610 17:53:26.182937       1 common.go:111] Probing CSI driver for readiness
I0610 17:53:26.183299       1 connection.go:183] GRPC call: /csi.v1.Identity/Probe
I0610 17:53:26.183582       1 connection.go:184] GRPC request: {}
I0610 17:53:26.205099       1 connection.go:186] GRPC response: {}
I0610 17:53:26.205354       1 connection.go:187] GRPC error: rpc error: code = Internal desc = TypeError: Cannot read properties of undefined (reading 'datasetParentName') TypeError: Cannot read properties of undefined (reading 'datasetParentName')
    at FreeNASSshDriver.getDatasetParentName (/home/csi/app/src/driver/controller-zfs/index.js:174:46)
    at FreeNASSshDriver.getVolumeParentDatasetName (/home/csi/app/src/driver/controller-zfs/index.js:180:34)
    at FreeNASSshDriver.Probe (/home/csi/app/src/driver/controller-zfs/index.js:545:36)
    at requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:49)
    at Object.Probe (/home/csi/app/bin/democratic-csi:290:7)
    at handleUnary (/home/csi/app/node_modules/@grpc/grpc-js/build/src/server.js:688:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
E0610 17:53:26.205600       1 csi-provisioner.go:197] CSI driver probe failed: rpc error: code = Internal desc = TypeError: Cannot read properties of undefined (reading 'datasetParentName') TypeError: Cannot read properties of undefined (reading 'datasetParentName')
    at FreeNASSshDriver.getDatasetParentName (/home/csi/app/src/driver/controller-zfs/index.js:174:46)
    at FreeNASSshDriver.getVolumeParentDatasetName (/home/csi/app/src/driver/controller-zfs/index.js:180:34)
    at FreeNASSshDriver.Probe (/home/csi/app/src/driver/controller-zfs/index.js:545:36)
    at requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:49)
    at Object.Probe (/home/csi/app/bin/democratic-csi:290:7)
    at handleUnary (/home/csi/app/node_modules/@grpc/grpc-js/build/src/server.js:688:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
I have these pools created:
![image](https://user-images.githubusercontent.com/7469656/173124357-16028bb8-1685-4f0c-be69-d7982611d07f.png)

I am installing via helm using:

```
-> helm upgrade --install --create-namespace --values ./freenas-nfs.yaml --namespace democratic-csi zfs-nfs democratic-csi/democratic-csi
Release "zfs-nfs" does not exist. Installing it now.
NAME: zfs-nfs
LAST DEPLOYED: Fri Jun 10 11:52:55 2022
NAMESPACE: democratic-csi
STATUS: deployed
REVISION: 1
TEST SUITE: None
```

This is my values.yaml:
```
csiDriver:
  # should be globally unique for a given cluster
  name: "org.democratic-csi.nfs"

# add note here about volume expansion requirements
storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    # for block-based storage can be ext3, ext4, xfs
    # for nfs should be nfs
    fsType: nfs
      
    # if true, volumes created from other snapshots will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromSnapshots: "false"
    
    # if true, volumes created from other volumes will be
    # zfs send/received instead of zfs cloned
    # detachedVolumesFromVolumes: "false"

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

# if your cluster supports snapshots you may enable below
volumeSnapshotClasses: []
#- name: freenas-nfs-csi
#  parameters:
#  # if true, snapshots will be created with zfs send/receive
#  # detachedSnapshots: "false"
#  secrets:
#    snapshotter-secret:

driver:
  config:
    driver: freenas-nfs
    instance_id: abcde-feghij
httpConnection:
  protocol: https
  host: 172.30.203.15
  port: 443
  # use only 1 of apiKey or username/password
  # if both are present, apiKey is preferred
  # apiKey is only available starting in TrueNAS-12
  apiKey: <redacted>
  #username: root
  #password: 
  allowInsecure: true
  # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
  # leave unset for auto-detection
  apiVersion: 2
sshConnection:
  host: 172.30.203.15
  port: 22
  username: csi-user
  # use either password or key
  # password:
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    ...
    -----END RSA PRIVATE KEY-----
zfs:
  cli:
    sudoEnabled: true
  #datasetProperties:
  #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  #  "org.freenas:test": "{{ parameters.foo }}"
  #  "org.freenas:test2": "some value"

  datasetParentName: tkfstorage/k8s/nfs/vols
  # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
  # they may be siblings, but neither should be nested in the other
  detachedSnapshotsDatasetParentName: tkfstorage/k8s/nfs/snaps
  datasetEnableQuotas: true
  datasetEnableReservation: false
  datasetPermissionsMode: "0777"
  datasetPermissionsUser: csi-user
  datasetPermissionsGroup: wheel
  #datasetPermissionsAcls:
  #- "-m everyone@:full_set:allow"
  #- "-m u:kube:full_set:allow"

nfs:
  #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
  shareHost: 172.30.203.15
  shareAlldirs: false
  shareAllowedHosts: []
  shareAllowedNetworks: []
  shareMaprootUser: root
  shareMaprootGroup: wheel
  shareMapallUser: ""
  shareMapallGroup: ""
```

**Comment by travisghansen** [comment]
The `driver.config` block is incorrect (or rather in your file every thing below it should be scoped in `driver.config`:

```
...
driver:
  config:
    driver: freenas-nfs
    instance_id: abcde-feghij
    httpConnection:
      protocol: https
      host: 172.30.203.15
      port: 443
      # use only 1 of apiKey or username/password
      # if both are present, apiKey is preferred
      # apiKey is only available starting in TrueNAS-12
      apiKey: <redacted>
      #username: root
      #password: 
      allowInsecure: true
      # use apiVersion 2 for TrueNAS-12 and up (will work on 11.x in some scenarios as well)
      # leave unset for auto-detection
      apiVersion: 2
    sshConnection:
      host: 172.30.203.15
      port: 22
      username: csi-user
      # use either password or key
      # password:
      privateKey: |
        -----BEGIN RSA PRIVATE KEY-----
        ...
        -----END RSA PRIVATE KEY-----
    zfs:
      cli:
        sudoEnabled: true
      #datasetProperties:
      #  "org.freenas:description": "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}/{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      #  "org.freenas:test": "{{ parameters.foo }}"
      #  "org.freenas:test2": "some value"
    
      datasetParentName: tkfstorage/k8s/nfs/vols
      # do NOT make datasetParentName and detachedSnapshotsDatasetParentName overlap
      # they may be siblings, but neither should be nested in the other
      detachedSnapshotsDatasetParentName: tkfstorage/k8s/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: csi-user
      datasetPermissionsGroup: wheel
      #datasetPermissionsAcls:
      #- "-m everyone@:full_set:allow"
      #- "-m u:kube:full_set:allow"
    
    nfs:
      #shareCommentTemplate: "{{ parameters.[csi.storage.k8s.io/pvc/namespace] }}-{{ parameters.[csi.storage.k8s.io/pvc/name] }}"
      shareHost: 172.30.203.15
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```

**Comment by teknofile** [comment]
Doh.

Thanks!
