### ISSUE TITLE
iSCSI Kernel Messages

### ISSUE THREAD

**Issue by reefland** [democratic-csi/democratic-csi#216]
Got an alert that Prometheus had a problem with compacting blocks (using an iSCSI PVC), has about 8 GiB free space still.  I checked the kernel logs on the node hosting Prometheus and found the entries below.  Not sure what they mean, but figured I'd document it here it case it is useful, if not we can just close the issue.   There wasn't an issue with TrueNAS, it was up and running and no outages or issues with it.  

```
|Jul 11 09:00:11 k3s01 kernel: [343031.095444]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:11 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:13 k3s01 kernel: [343033.112804] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:13 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:18 k3s01 kernel: [343038.136438]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:18 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:20 k3s01 kernel: [343040.152722] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:20 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:25 k3s01 kernel: [343045.139682]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:25 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:28 k3s01 kernel: [343048.156800] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:28 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:33 k3s01 kernel: [343053.141647]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:33 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:37 k3s01 kernel: [343057.161031] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:37 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:42 k3s01 kernel: [343062.231074]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:43 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:44 k3s01 kernel: [343064.252751] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:45 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:47 k3s01 kernel: [343067.536233]  connection1:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:48 k3s01 iscsid: Kernel reported iSCSI connection 1:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352159]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:49 k3s01 kernel: [343069.352284] scsi_io_completion_action: 13 callbacks suppressed                                                                        │
│Jul 11 09:00:49 k3s01 kernel: [343069.352291] sd 2:0:0:0: [sdc] tag#29 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352297] sd 2:0:0:0: [sdc] tag#29 CDB: Write(10) 2a 00 00 07 9e 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352298] print_req_error: 13 callbacks suppressed                                                                                  │
│Jul 11 09:00:49 k3s01 kernel: [343069.352302] blk_update_request: I/O error, dev sdc, sector 3994320 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352389] sd 2:0:0:0: [sdc] tag#30 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352392] sd 2:0:0:0: [sdc] tag#30 CDB: Write(10) 2a 00 00 07 99 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352394] blk_update_request: I/O error, dev sdc, sector 3984080 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352460] sd 2:0:0:0: [sdc] tag#31 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352462] sd 2:0:0:0: [sdc] tag#31 CDB: Write(10) 2a 00 00 07 97 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352464] blk_update_request: I/O error, dev sdc, sector 3979984 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352529] sd 2:0:0:0: [sdc] tag#35 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352531] sd 2:0:0:0: [sdc] tag#35 CDB: Write(10) 2a 00 00 07 96 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352533] blk_update_request: I/O error, dev sdc, sector 3977936 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352599] sd 2:0:0:0: [sdc] tag#26 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352601] sd 2:0:0:0: [sdc] tag#26 CDB: Write(10) 2a 00 00 07 a8 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352603] blk_update_request: I/O error, dev sdc, sector 4014800 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352667] sd 2:0:0:0: [sdc] tag#36 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352669] sd 2:0:0:0: [sdc] tag#36 CDB: Write(10) 2a 00 00 07 9b 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352671] blk_update_request: I/O error, dev sdc, sector 3988176 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352736] sd 2:0:0:0: [sdc] tag#37 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352738] sd 2:0:0:0: [sdc] tag#37 CDB: Write(10) 2a 00 00 07 9c 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352740] blk_update_request: I/O error, dev sdc, sector 3990224 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352804] sd 2:0:0:0: [sdc] tag#38 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352806] sd 2:0:0:0: [sdc] tag#38 CDB: Write(10) 2a 00 00 07 a0 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352807] blk_update_request: I/O error, dev sdc, sector 3998416 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352871] sd 2:0:0:0: [sdc] tag#39 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352873] sd 2:0:0:0: [sdc] tag#39 CDB: Write(10) 2a 00 00 07 a1 5a 00 01 00 00                                                     │
│Jul 11 09:00:49 k3s01 kernel: [343069.352875] blk_update_request: I/O error, dev sdc, sector 4000464 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:49 k3s01 kernel: [343069.352939] sd 2:0:0:0: [sdc] tag#28 FAILED Result: hostbyte=DID_TRANSPORT_DISRUPTED driverbyte=DRIVER_OK                             │
│Jul 11 09:00:49 k3s01 kernel: [343069.352940] sd 2:0:0:0: [sdc] tag#28 CDB: Write(10) 2a 00 00 07 a9 5a 00 01 00 00
|Jul 11 09:00:49 k3s01 kernel: [343069.352942] blk_update_request: I/O error, dev sdc, sector 4016848 op 0x1:(WRITE) flags 0x4800 phys_seg 256 prio class 0              │
│Jul 11 09:00:50 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:51 k3s01 iscsid: connection1:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:51 k3s01 kernel: [343071.365756] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:52 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)                                                                                  │
│Jul 11 09:00:56 k3s01 kernel: [343076.423472]  connection2:0: detected conn error (1020)                                                                                │
│Jul 11 09:00:57 k3s01 iscsid: Kernel reported iSCSI connection 2:0 error (1020 - ISCSI_ERR_TCP_CONN_CLOSE: TCP connection closed) state (3)                             │
│Jul 11 09:00:58 k3s01 kernel: [343078.444692] sd 2:0:0:0: Power-on or device reset occurred                                                                             │
│Jul 11 09:00:58 k3s01 kernel: [343078.555498] XFS (sdc): writeback error on sector 4055304                                                                              │
│Jul 11 09:00:59 k3s01 iscsid: connection2:0 is operational after recovery (1 attempts)
```

Looking at the Prometheus container logs, it looks like this caused a container restart and its been fine since.  Previous container log ended with:

```
ts=2022-07-10T03:00:24.393Z caller=head.go:1009 level=info component=tsdb msg="WAL checkpoint complete" first=1751 last=1756 duration=5.742387925s
panic: sync /prometheus/chunks_head/000548: input/output error

goroutine 13676 [running]:
github.com/prometheus/prometheus/tsdb.handleChunkWriteError({0x38910c0?, 0xc0b18f5ef0?})
	/app/tsdb/head_append.go:598 +0x76
github.com/prometheus/prometheus/tsdb/chunks.(*ChunkDiskMapper).WriteChunk(0xc000be2000, 0x40d9a7?, 0x28?, 0x2cedbc0?, {0x38b3380, 0xc09fa94380}, 0x3489870)
	/app/tsdb/chunks/head_chunks.go:392 +0x151
github.com/prometheus/prometheus/tsdb.(*memSeries).mmapCurrentHeadChunk(0xc016f242a0, 0x60bce7d4?)
	/app/tsdb/head_append.go:587 +0x53
github.com/prometheus/prometheus/tsdb.(*memSeries).cutNewHeadChunk(0xc016f242a0, 0x181e67a9b43, 0x4070400000000000?)
	/app/tsdb/head_append.go:561 +0x2a
github.com/prometheus/prometheus/tsdb.(*memSeries).append(0xc016f242a0, 0x181e67a9b43, 0x4070400000000000, 0x2074f8, 0x2385565?)
	/app/tsdb/head_append.go:528 +0x1a5
github.com/prometheus/prometheus/tsdb.(*headAppender).Commit(0xc04e9ef540)
	/app/tsdb/head_append.go:459 +0x612
github.com/prometheus/prometheus/tsdb.dbAppender.Commit({{0x38acd48?, 0xc04e9ef540?}, 0xc000b18820?})
	/app/tsdb/db.go:870 +0x35
github.com/prometheus/prometheus/storage.(*fanoutAppender).Commit(0xc050290300)
	/app/storage/fanout.go:176 +0x3f
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport.func1()
	/app/scrape/scrape.go:1271 +0x45
github.com/prometheus/prometheus/scrape.(*scrapeLoop).scrapeAndReport(0xc09420ed20, {0xeda5c53d3?, 0x4faeaa0?, 0x4faeaa0?}, {0xeda5c53d3?, 0x4faeaa0?, 0x4faeaa0?}, 0x0)
	/app/scrape/scrape.go:1342 +0xf70
github.com/prometheus/prometheus/scrape.(*scrapeLoop).run(0xc09420ed20, 0xc09418f830?)
	/app/scrape/scrape.go:1224 +0x345
created by github.com/prometheus/prometheus/scrape.(*scrapePool).sync
	/app/scrape/scrape.go:588 +0xa1e
```

**Comment by travisghansen** [comment]
That appears to indicate the networking between the 2 hosts had some intermittent connectivity issues. There are parameters in the ‘db’ configuration for the target that can alter relevant timeouts etc should you ever want to tweak those.

Also of note, my experience has been that once an issue like this occurs (perhaps not this exact issue, but connectivity issues in general) when the connection does come back up the device/fs is read only. The easiest way resolve that is do as you did and delete the pod and let it restart.

**Comment by reefland** [comment]
ok, makes sense...  I'll close the issue.   I did see some notes on the TrueNAS side which agrees with some connectivity issues. Weird, they are both on the same switch.

```
Jul 11 09:00:11 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): no ping reply (NOP-Out) after 5 seconds; dropping connection
Jul 11 09:00:11 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): waiting for CTL to terminate 15 tasks
Jul 11 09:00:11 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): tasks terminated
Jul 11 09:00:18 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): no ping reply (NOP-Out) after 5 seconds; dropping connection
Jul 11 09:00:18 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): waiting for CTL to terminate 17 tasks
Jul 11 09:00:18 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): tasks terminated
Jul 11 09:00:19 truenas kernel: Limiting open port RST response from 314 to 200 packets/sec
Jul 11 09:00:25 truenas kernel[2136]: Last message 'Limiting open port R' repeated 1 times, suppressed by syslog-ng on truenas
Jul 11 09:00:25 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): no ping reply (NOP-Out) after 5 seconds; dropping connection
Jul 11 09:00:25 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): waiting for CTL to terminate 19 tasks
Jul 11 09:00:25 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): tasks terminated
Jul 11 09:00:27 truenas kernel: Limiting open port RST response from 333 to 200 packets/sec
Jul 11 09:00:33 truenas kernel[2136]: Last message 'Limiting open port R' repeated 1 times, suppressed by syslog-ng on truenas
Jul 11 09:00:33 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): no ping reply (NOP-Out) after 5 seconds; dropping connection
Jul 11 09:00:33 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): waiting for CTL to terminate 21 tasks
Jul 11 09:00:33 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): tasks terminated
Jul 11 09:00:36 truenas kernel: Limiting open port RST response from 240 to 200 packets/sec
Jul 11 09:00:42 truenas kernel[2136]: Last message 'Limiting open port R' repeated 1 times, suppressed by syslog-ng on truenas
Jul 11 09:00:42 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): no ping reply (NOP-Out) after 5 seconds; dropping connection
Jul 11 09:00:42 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): waiting for CTL to terminate 22 tasks
Jul 11 09:00:42 truenas WARNING: 192.168.10.215 (iqn.1993-08.org.debian:01:bddd1e9c267): tasks terminated
Jul 11 09:00:44 truenas kernel: Limiting open port RST response from 279 to 200 packets/sec
```

**Comment by reefland** [comment]
One more comment...  The notices about `Limiting open port RST response from 278 to 200 packets/sec` - long history of people asking about these message in BSD.   Typically you ignore.  An RST response is sent to a client who sends a SYN to a closed port.   I did a `tcpdump` to see who was being send the RST.   Interesting...

TrueNAS is sending a RST to the Kubernetes node using iSCSI and its on the iSCSI portal listener port which should not be closed. This happens right on the hour (just like above), so doesn't seem random.

```
root@truenas[~]# tcpdump -n -v 'tcp[tcpflags] & (tcp-rst) != 0'

tcpdump: listening on sfxge1, link-type EN10MB (Ethernet), capture size 262144 bytes
11:00:29.260287 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40, bad cksum 0 (->a442)!)
    192.168.10.102.3260 > 192.168.10.215.43434: Flags [R], cksum 0x96a8 (incorrect -> 0x0d39), seq 2463482589, win 0, length 0
.... repeats a few hundred times...

11:00:29.260808 IP (tos 0x0, ttl 64, id 49365, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.10.215.43434 > 192.168.10.102.3260: Flags [R.], cksum 0x04be (correct), seq 1805416207, ack 2463482830, win 52886, options [nop,nop,TS val 2843230250 ecr 2227416761], length 0
11:00:29.260815 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    192.168.10.215.43434 > 192.168.10.102.3260: Flags [R], cksum 0x5eb7 (correct), seq 1804966047, win 0, length 0
11:00:29.260829 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    192.168.10.215.43434 > 192.168.10.102.3260: Flags [R], cksum 0x5eb7 (correct), seq 1804966047, win 0, length 0
11:00:29.260834 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    192.168.10.215.43434 > 192.168.10.102.3260: Flags [R], cksum 0x5eb7 (correct), seq 1804966047, win 0, length 0
11:00:50.827676 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40, bad cksum 0 (->a442)!)
    192.168.10.102.3260 > 192.168.10.215.49878: Flags [R], cksum 0x96a8 (incorrect -> 0x14ea), seq 2721551006, win 0, length 0
.... repeats a few hundred times...

11:00:50.828074 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40, bad cksum 0 (->a442)!)
    192.168.10.102.3260 > 192.168.10.215.49878: Flags [R], cksum 0x96a8 (incorrect -> 0x14ea), seq 2721551006, win 0, length 0
11:00:50.828156 IP (tos 0x0, ttl 64, id 12794, offset 0, flags [DF], proto TCP (6), length 52)
    192.168.10.215.49878 > 192.168.10.102.3260: Flags [R.], cksum 0x1074 (correct), seq 633014610, ack 2721551247, win 16652, options [nop,nop,TS val 2843251388 ecr 1437059175], length 0
11:00:50.828157 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    192.168.10.215.49878 > 192.168.10.102.3260: Flags [R], cksum 0xedf0 (correct), seq 632632858, win 0, length 0
11:00:50.828160 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    192.168.10.215.49878 > 192.168.10.102.3260: Flags [R], cksum 0xedf0 (correct), seq 632632858, win 0, length 0
11:00:50.828162 IP (tos 0x0, ttl 64, id 0, offset 0, flags [DF], proto TCP (6), length 40)
    192.168.10.215.49878 > 192.168.10.102.3260: Flags [R], cksum 0xedf0 (correct), seq 632632858, win 0, length 
```
All of that is within 1 minutes time, same as original post above.

If I understand that correctly, kubernetes node `192.168.10.215` was trying to connect to truenas `92.168.10.102` on port `3260` which is the iSCSI Portal Listen port.

Once that 1 minute is up, it goes silent again.  Not seen anything since.

Doesn't seem to be many connections to port `3260`:

```
root@truenas[~]# sockstat -P TCP -p 3260
USER     COMMAND    PID   FD PROTO  LOCAL ADDRESS         FOREIGN ADDRESS      
root     ctld       1229  7  tcp4   192.168.10.102:3260   *:*
?        ?          ?     ?  tcp4   192.168.10.102:3260   192.168.10.216:33714
?        ?          ?     ?  tcp4   192.168.10.102:3260   192.168.10.215:40734
?        ?          ?     ?  tcp4   192.168.10.102:3260   192.168.10.215:52774
```

Not sure what it means...

**Comment by travisghansen** [comment]
Is there some cron job which is locking things up from being overloaded or something?

**Comment by reefland** [comment]
It looks like Prometheus itself is doing something every 2 hours to free up disk space:
![prometheus_compaction_2_hrs](https://user-images.githubusercontent.com/16230914/178312935-f06802b3-cc17-4a34-a03c-461a8c87b31f.png)

Any CSI tweaks needed for bursty disk activity?

**Comment by travisghansen** [comment]
Prometheus is likely just doing some garbage collection and/or compression on the 2 hour interval.

Not particularly any tweaks no. You can rifle through the 'node' files in `/etc/iscsi/nodes/` and see all the configuration parameters however and see if something makes sense to tweak in your particular setup. I'm honestly not the most knowledgeable about tweaking neither the server nor client side of the equation so unfortunately don't have much to offer :(

**Comment by reefland** [comment]
Not a single RST message logged since I disable that hourly snapshot. I'll keep monitoring it. I don't really need hourly snapshots, I'll leave it disabled for now and keep the nightly.  If I do enable, I'll make it not exactly on the hour. 

 Thanks for the comments, it's appreciated.
