### ISSUE TITLE
 Could not log into all portals

### ISSUE THREAD

**Issue by D1StrX** [democratic-csi/democratic-csi#269]
For somereason after recreating the same pvcs (the displayname) or too many times after each other on Truenas scale Bluefin I see this error:
I saw similar posts from the past, but unfortunately they didn't provide much new information for me.
```
MountVolume.MountDevice failed for volume "pvc-b5aa51ab-xxxx-x-xxx" : rpc error: code = Internal desc = {"code":19,"stdout":"Logging in to [iface: default, target: <iqn>:<pvc-display-name>, portal: <ipaddress_portal>,<port>]\n","stderr":"iscsiadm: Could not login to [iface: default, target: <iqn>:<pvc-display-name>, portal: <ipaddress_portal>,<port>].\niscsiadm: initiator reported error (19 - encountered non-retryable iSCSI login failure)\niscsiadm: Could not log into all portals\n","timeout":false}
```

**Comment by travisghansen** [comment]
Check the logs on NAS side, on SCALE it's something like this: `journalctl -xef --unit scst.service`

In the past the (on CORE specifically) there were scenarios where the iscsi daemon config file would have concurrency issues writing to it and it would end up in a bad state. On SCALE I don't recall seeing this, but the file is:

```
cat /etc/scst.conf 
HANDLER vdisk_fileio {
}
HANDLER vdisk_blockio {
}

TARGET_DRIVER iscsi {
    enabled 1

}
```

**Comment by D1StrX** [comment]
`journalctl -xef --unit scst.service` results show connected connections from they kubernetes workers nodes. No errors there.
In the `/etc/scst.conf ` file are the handlers.Device the pvc's in the paths not matching/missing the ones in kubernetes and the logging of the pod. (Just the latest pods which I am working with right now)

**Comment by travisghansen** [comment]
Is everything in the file that shows in the NAS ui? If not to get it to rebuild you can probably start/stop the service (from the UI) or `midclt call etc.generate scst` and then restart/reload `scst` service.

**Comment by D1StrX** [comment]
All pvcs were created and visible in the Truenas UI. Restarts works (did a full reboot earlier today). Now, after 45m doing nothing and deleting the deployment and created pvcs, the pods are running. It is just a weird thing when performing multiple operations in a short amount of time, the provisioner/truenas stresses out.

**Comment by travisghansen** [comment]
Yeah, if you think there's a bug in regenerating that file/concurrency issues let me know. There are supposed to be locks on the TrueNAS side which prevent multiple concurrent api requests from blowing things up.

**Comment by D1StrX** [comment]
Will probably hit it again soon. Will let you know.

**Comment by D1StrX** [comment]
Happened again:
In the Truenas UI the PVC is created. In /etc/scst.conf for DEVICE it is created. But no TARGET. 
```
cat /etc/scst.conf| grep pvc-5974d25b-xxxx-xxx
filename /path/to/pvc-5974d25b-xxxx-xxx
```

Guessing this is the bug indeed

**Comment by travisghansen** [comment]
Is the target in the ui and associated with the device?

**Comment by D1StrX** [comment]
It is in the UI.
I see there the extent + target

**Comment by travisghansen** [comment]
And is the extent associated to the target as well?

**Comment by D1StrX** [comment]
associated targets as well.

**Comment by travisghansen** [comment]
Ok so regen by itself is enough to fix the conf file?

**Comment by D1StrX** [comment]
restarted the service via UI. Can't start it atm, because of it can't/doesn't regen the conf file:
Logs show it is going through all targets etc (or whatever it is called) and fails on the one I just wrote about. 

Feb 04 20:43:56 None[1070438]: -> Setting device attribute 'prod_id' to value 'iSCSI Disk' for device '<device_name>-cluster01': done. Feb 04 20:43:56 None[1070438]: -> 
Opening device '<another_device_name>' using handler 'vdisk_blockio': done. Feb 04 20:43:56 None[1070438]: FATAL: Received the following error: Feb 04 20:43:56 None[1070438]: Failed to open device. See "dmesg" for more information.

**Comment by travisghansen** [comment]
`midclt call etc.generate scst` and then check the file.

**Comment by D1StrX** [comment]
midclt call etc.generate scst
null

**Comment by travisghansen** [comment]
Does the config file look proper now though? That command won't restart the service... you can `systemctl restart scst.service`.

**Comment by D1StrX** [comment]
No, because only DEVICE is filled. It didn't add TARGET. 
Understood that the command regens the conf file.

**Comment by travisghansen** [comment]
Wait, so the UI shows everything appropriate but after running the midctl command the file still isn't correct?

**Comment by D1StrX** [comment]
also systemctl restart scst.service from cli doesn't work (kinda expacted)

**Comment by D1StrX** [comment]
> Wait, so the UI shows everything appropriate but after running the midctl command the file still isn't correct?

Indeed.

**Comment by D1StrX** [comment]
cat /etc/scst.conf| grep -A 10 pvc-5974d25b-xxxx.xxxx -B 20

Only returns DEVICE. Expecting more results (TARGET)

**Comment by D1StrX** [comment]
Crap... wrong grep. Can't confirm now if  TARGET was filled or not. It is there right now

**Comment by travisghansen** [comment]
That sounds like a nasty bug yeah. @yocalebo any thoughts?

**Comment by travisghansen** [comment]
Any logs from the service/journalctl that should why it's blowing up? Save a copy of the config in it's current state so it can be reviewed.

**Comment by D1StrX** [comment]
Saved journal. Saved Debug via Advanced settings. Please let me through you/IX systems know what exactly is needed.

**Comment by D1StrX** [comment]
After reboot, ISCSI service restarted with state running. But it wasn't oke. So stopped and tried to restart. Same error. After manually removing  the PVC from the Truenas scale gui, the iscsi service started and it is is back "working".

**Comment by travisghansen** [comment]
hmm, sounds like something was messed up with the db...should have had you save that too :(

**Comment by D1StrX** [comment]
how? The start error is in current session saved.

**Comment by D1StrX** [comment]
I found some other relevant logs from the ISCSI GUI:
ISCSI service -> Edit portal -> Save (didn't change any details)
Description, CHAP, discovery group, ipadress is filled.

```
 Error: Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: services_iscsitargetportalip.iscsi_target_portalip_ip

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 181, in call_method
    result = await self.middleware._call(message['method'], serviceobj, methodobj, params, app=self)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1255, in _call
    return await methodobj(*prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/service.py", line 933, in update
    rv = await self.middleware._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1255, in _call
    return await methodobj(*prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1152, in nf
    res = await f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1284, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/iscsi_/portal.py", line 229, in do_update
    await self.__save_listen(pk, listen, old['listen'])
  File "/usr/lib/python3/dist-packages/middlewared/plugins/iscsi_/portal.py", line 182, in __save_listen
    await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1306, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1255, in _call
    return await methodobj(*prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/schema.py", line 1284, in nf
    return await func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/datastore/write.py", line 62, in insert
    result = await self.middleware.call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1306, in call
    return await self._call(
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1266, in _call
    return await self.run_in_executor(prepared_call.executor, methodobj, *prepared_call.args)
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1169, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/middlewared/plugins/datastore/connection.py", line 75, in execute_write
    result = self.connection.execute(sql, binds)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/lib/python3/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/lib/python3/dist-packages/sqlalchemy/engine/default.py", line 609, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: services_iscsitargetportalip.iscsi_target_portalip_ip
[SQL: INSERT INTO services_iscsitargetportalip (iscsi_target_portalip_portal_id, iscsi_target_portalip_ip) VALUES (?, ?)]
[parameters: (2, '<portal_ip>')]
(Background on this error at: http://sqlalche.me/e/13/gkpj)
```

**Comment by travisghansen** [comment]
That sounds like another bug if the name is to be trusted. The constraint should be ip+port not just ip.

**Comment by D1StrX** [comment]
Tried to contact IX-Systems via Jira (mostly regarding the second bug), which redirects me to servicedesk. Tried to create one there, immediately set to done. Discord wasn't an success either. Do you perhaps have other suggestions?

**Comment by kmoore134** [comment]
@D1StrX - I'm trying to figure out why you couldn't report a ticket on Jira. When you go to https://ixsystems.atlassian.net do you have a log-in button top right that lets you make an account? 

![image](https://user-images.githubusercontent.com/1933088/217082480-b5e1ab3d-99f4-4b37-9a98-83309ef7ce15.png)

**Comment by D1StrX** [comment]
yes, and when I signed in with an Atlassian account and click on _Create_ I am redirected to the servicedesk.

**Comment by kmoore134** [comment]
Interesting, I just made a new account and cannot reproduce here. Can you send me your email address you used for your Jira account and I'll check settings to make sure on our end its not screwy? 

kris [ at ] ixsystems.com

**Comment by D1StrX** [comment]
Just sent you an email

**Comment by D1StrX** [comment]
https://ixsystems.atlassian.net/browse/TC-2575 is created regarding the IntegrityError.

**Comment by D1StrX** [comment]
@travisghansen The second bug should be fixed in next or next release. Any news on the iscsi portal login one?
That one is starting to hurt :disappointed_relieved:

**Comment by D1StrX** [comment]
I have the idea that the naming scheme is the problem of my pods -> truenas. Iscsi 63 characters max limit thing.
Could the CSI driver do a validation on the name length?

**Comment by travisghansen** [comment]
I think it does do validation, but that really isn’t valid anymore. Linux doesn’t have that limit and freebsd 13 doesn’t have the (same) limit either. In both cases the limit is now 255 I believe.

The portal issue isn’t an issue with the driver. If the config isn’t correct then it won’t login to the portal so there isn’t really anything I can do about that (unless the config on the server is valid and it still throws the login error, in which case something else entirely is going on).

**Comment by D1StrX** [comment]
@travisghansen should a Jira ticket be made for the portal login issue? Haven't heard from yocalebo so far I can see
Issue is still ongoing

**Comment by travisghansen** [comment]
Yeah if you see everything in the ui but it is not correctly showing in the conf file for the iscsi daemon then it’s definitely something that needs to be addressed.

**Comment by D1StrX** [comment]
Created Jira ticket: https://ixsystems.atlassian.net/browse/NAS-120980

**Comment by D1StrX** [comment]
Got news, found the issue:

**Kern.log** in the debugs of truenas

ERROR: Name prefix-name-to-fill-up-the-length-to-be-more-then-64-chars-suffix is too long (max allowed 64)


> I think it does do validation, but 63 really isn’t valid anymore. Linux doesn’t have that limit and freebsd 13 doesn’t have the (same) limit either. In both cases the limit is now 255 I believe. There is code that detects at runtime if there’s an issue based on the os/version which effectively uses the logic mentioned.
> 
> * https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/controller-zfs/index.js#L414
> * https://github.com/democratic-csi/democratic-csi/blob/master/src/driver/freenas/api.js#L2101
> 
> The portal issue isn’t an issue with the driver. If the config isn’t correct then it won’t login to the portal so there isn’t really anything I can do about that (unless the config on the server is valid and it still throws the login error, in which case something else entirely is going on).

I am safe to say, told you? 😉 😂

**Comment by travisghansen** [comment]
Interesting. Those are different limits FYI. Guess I need to add more logic. Is there some `scst` doc that goes over that limit that you've found?

**Comment by D1StrX** [comment]
I understand, exactly that I mentioned in the Jira ticket. The only thing I can find, also based on the documentation of iX systems:
https://www.truenas.com/docs/scale/scaletutorials/shares/iscsi/addingiscsishares/#iscsi-manual-setup -> [RFC3721](https://tools.ietf.org/html/rfc3721.html).
-> https://www.rfc-editor.org/rfc/rfc3720#section-3.2.6.3.2

But it never states a limit of 64 characters.

**Comment by D1StrX** [comment]
> Interesting. Those are different limits FYI. Guess I need to add more logic. Is there some `scst` doc that goes over that limit that you've found?

https://ixsystems.atlassian.net/browse/NAS-120980 they hardcoded it into their end

**Comment by travisghansen** [comment]
Does it apply to targets and extents? Do we know if CORE has the same limits?

**Comment by D1StrX** [comment]
No clue, probably have to verify/read the commits.

**Comment by D1StrX** [comment]
rrpc error: code = Internal desc = {"code":19,"stdout":"Logging in to [iface: default, target: iqn<iscsiportal>:<pvc>, portal: <portal_ip>]\n","stderr":"iscsiadm: Could not login to [iface: default, target: iqn iqn<iscsiportal>:<pvc>, portal: <portal_ip>].\niscsiadm: initiator reported error (19 - encountered non-retryable iSCSI login failure)\niscsiadm: Could not log into all portals\n","timeout":false}

@travisghansen Here we go again 😢 Never really got stable yet, but currently running on chart 0.14.1. Scale on version 22.12.3.1.

Attach required etc is configured, as of the changelog. But still getting random this error upon restarting pods, re-recreating pods etc.

**Comment by travisghansen** [comment]
The daemon config file is sane?

**Comment by D1StrX** [comment]
got to get back to you for that. After retrying and deleting it a bunch of times, including the controller, it "fixes" itself.
Currently it looks sane.

**Comment by D1StrX** [comment]
I have new news, and might found an/the issue. I did `journalctl -xef --unit scst.service` when the issue occured again on TrueNas Scale. 
```
 Initiator iqn......ubuntu:01:something not allowed to connect to target iqn......org.freenas.ctl:<iscsi_target_name>
```
No clue why this happens, since initiators got no list set. And CHAP is used. 

when performing cat /etc/scst.conf:
    DEVICE <target_name> {
        filename /path/to/pvc-.....-56b45cbb0ef9
        blocksize 512
        lb_per_pb_exp 0
        read_only 0
        usn <usn>
        naa_id <id>
        prod_id "iSCSI Disk"
        rotational 1
        t10_vend_id TrueNAS
        t10_dev_id <number> 
    }

**Comment by travisghansen** [comment]
What do you feel may be the issue? Is the file corrupt and not formatted correctly?

**Comment by D1StrX** [comment]
the file looks fine. But it feels like random authentication issues for no reason 'not allowed to connect'. Why could this be?
