### ISSUE TITLE
Cannot create more than 1 freenas-smb volume through Nomad

### ISSUE THREAD

**Issue by dcarbone** [democratic-csi/democratic-csi#291]
Hey there,

Running into a really bizarre issue with the smb driver.  It works just fine when creating a single volume, but when creating the 2nd I get a circular reference error from the node:

```json
{"host":"153ae7fde038","level":"error","message":"handler error - driver: FreeNASSshDriver method: CreateVolume error: TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'res' -> object with constructor 'IncomingMessage'\n    --- property 'req' closes the circle TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'ClientRequest'\n    |     property 'res' -> object with constructor 'IncomingMessage'\n    --- property 'req' closes the circle\n    at JSON.stringify (<anonymous>)\n    at FreeNASSshDriver.findResourceByProperties (/home/csi/app/src/driver/freenas/ssh.js:174:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async FreeNASSshDriver.createShare (/home/csi/app/src/driver/freenas/ssh.js:643:37)\n    at async FreeNASSshDriver.CreateVolume (/home/csi/app/src/driver/controller-zfs/index.js:1213:22)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)","service":"democratic-csi","timestamp":"2023-04-10T02:02:57.247Z"}
```

I don't have this issue with my iscsi driver setup.

**Comment by travisghansen** [comment]
Can you send the logs of the controller pod? csi-driver container.

**Comment by dcarbone** [comment]
@travisghansen sorry for the delayed response!  here are logs from another attempt i made just now:

```json
[
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'validating capabilities: [{"access_mode":{"mode":"MULTI_NODE_SINGLE_WRITER"},"mount":{"mount_flags":[],"fs_type":"","volume_mount_group":""},"access_type":"mount"}]',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.199Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs get -Hp -o name,property,value,received,source volsize,refquota Leviathan/csi/sv/certman-certs-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.203Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'validating capabilities: [{"access_mode":{"mode":"MULTI_NODE_SINGLE_WRITER"},"mount":{"mount_flags":[],"fs_type":"","volume_mount_group":""},"access_type":"mount"}]',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.208Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs get -Hp -o name,property,value,received,source volsize,refquota Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.209Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs create -p -o aclmode="restricted" -o aclinherit="passthrough" -o acltype="nfsv4" -o casesensitivity="sensitive" -o democratic-csi:csi_volume_name="certman-certs-smb" -o democratic-csi:managed_resource="true" -o democratic-csi:volume_context_provisioner_driver="freenas-smb" -o democratic-csi:volume_context_provisioner_instance_id="5b2b5d60-0bfe-4439-8072-117b89f27890" Leviathan/csi/sv/certman-certs-smb',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.242Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs create -p -o aclmode="restricted" -o aclinherit="passthrough" -o acltype="nfsv4" -o casesensitivity="sensitive" -o democratic-csi:csi_volume_name="certman-config-smb" -o democratic-csi:managed_resource="true" -o democratic-csi:volume_context_provisioner_driver="freenas-smb" -o democratic-csi:volume_context_provisioner_instance_id="5b2b5d60-0bfe-4439-8072-117b89f27890" Leviathan/csi/sv/certman-config-smb',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.251Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs set refquota="1073741824" Leviathan/csi/sv/certman-config-smb',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:25.871Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs set refquota="1073741824" Leviathan/csi/sv/certman-certs-smb',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:26.060Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs get -Hp -o name,property,value,received,source mountpoint,refquota,compression,democratic-csi:csi_volume_name,democratic-csi:csi_volume_content_source_type,democratic-csi:csi_volume_content_source_id Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:26.273Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs get -Hp -o name,property,value,received,source mountpoint,refquota,compression,democratic-csi:csi_volume_name,democratic-csi:csi_volume_content_source_type,democratic-csi:csi_volume_content_source_id Leviathan/csi/sv/certman-certs-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:26.477Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "whoami command: whoami",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.673Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "set acl command: /usr/local/bin/sudo setfacl -m g:builtin_users:full_set:fd:allow /mnt/Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.689Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "whoami command: whoami",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.709Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "set acl command: /usr/local/bin/sudo setfacl -m group@:modify_set:fd:allow /mnt/Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.720Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "whoami command: whoami",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.732Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "whoami command: whoami",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.736Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "set acl command: /usr/local/bin/sudo setfacl -m g:builtin_users:full_set:fd:allow /mnt/Leviathan/csi/sv/certman-certs-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.742Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "set acl command: /usr/local/bin/sudo setfacl -m owner@:full_set:fd:allow /mnt/Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.747Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "whoami command: whoami",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.755Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs get -Hp -o name,property,value,received,source mountpoint,democratic-csi:freenas_smb_share_id Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.766Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "set acl command: /usr/local/bin/sudo setfacl -m group@:modify_set:fd:allow /mnt/Leviathan/csi/sv/certman-certs-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.772Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "whoami command: whoami",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.787Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": "FreeNAS creating smb share with name: csi-lev-",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.796Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "set acl command: /usr/local/bin/sudo setfacl -m owner@:full_set:fd:allow /mnt/Leviathan/csi/sv/certman-certs-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.814Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs get -Hp -o name,property,value,received,source mountpoint,democratic-csi:freenas_smb_share_id Leviathan/csi/sv/certman-certs-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.839Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": "FreeNAS creating smb share with name: csi-lev-",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:32.862Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "error",
    "message": "handler error - driver: FreeNASSshDriver method: CreateVolume error: TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle\n    at JSON.stringify (<anonymous>)\n    at FreeNASSshDriver.findResourceByProperties (/home/csi/app/src/driver/freenas/ssh.js:174:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async FreeNASSshDriver.createShare (/home/csi/app/src/driver/freenas/ssh.js:643:37)\n    at async FreeNASSshDriver.CreateVolume (/home/csi/app/src/driver/controller-zfs/index.js:1213:22)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:33.227Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs set democratic-csi:freenas_smb_share_id="31" Leviathan/csi/sv/certman-config-smb',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:37.372Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": "ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs set democratic-csi:csi_share_volume_context=\"{\\\"node_attach_driver\\\":\\\"smb\\\",\\\"server\\\":\\\"10.0.40.2\\\",\\\"share\\\":\\\"csi-lev-\\\"}\" Leviathan/csi/sv/certman-config-smb",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:37.572Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "verbose",
    "message": 'ZfsProcessManager command: /usr/local/bin/sudo /usr/local/sbin/zfs set democratic-csi:provision_success="true" Leviathan/csi/sv/certman-config-smb',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:37.808Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new response - driver: FreeNASSshDriver method: CreateVolume response: {"volume":{"volume_id":"certman-config-smb","capacity_bytes":"1073741824","content_source":null,"volume_context":{"node_attach_driver":"smb","server":"10.0.40.2","share":"csi-lev-","provisioner_driver":"freenas-smb","provisioner_driver_instance_id":"5b2b5d60-0bfe-4439-8072-117b89f27890"}}}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:38.064Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new request - driver: FreeNASSshDriver method: Probe call: {"metadata":{"user-agent":["grpc-go/1.53.0"]},"request":{},"cancelled":false}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:39.728Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new response - driver: FreeNASSshDriver method: Probe response: {"ready":{"value":true}}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:39.741Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new request - driver: FreeNASSshDriver method: Probe call: {"metadata":{"user-agent":["grpc-go/1.53.0"]},"request":{},"cancelled":false}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:39.808Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new response - driver: FreeNASSshDriver method: Probe response: {"ready":{"value":true}}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:39.822Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new request - driver: FreeNASSshDriver method: ControllerGetCapabilities call: {"metadata":{"user-agent":["grpc-go/1.53.0"]},"request":{},"cancelled":false}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:39.828Z",
  },
  {
    "host": "5e5a4bac29e9",
    "level": "info",
    "message": 'new response - driver: FreeNASSshDriver method: ControllerGetCapabilities response: {"capabilities":[{"rpc":{"type":"CREATE_DELETE_VOLUME"}},{"rpc":{"type":"LIST_VOLUMES"}},{"rpc":{"type":"GET_CAPACITY"}},{"rpc":{"type":"CREATE_DELETE_SNAPSHOT"}},{"rpc":{"type":"LIST_SNAPSHOTS"}},{"rpc":{"type":"CLONE_VOLUME"}},{"rpc":{"type":"EXPAND_VOLUME"}},{"rpc":{"type":"GET_VOLUME"}},{"rpc":{"type":"SINGLE_NODE_MULTI_WRITER"}}]}',
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:39.828Z",
  },
]
```

The entry of note:

```json
  {
    "host": "5e5a4bac29e9",
    "level": "error",
    "message": "handler error - driver: FreeNASSshDriver method: CreateVolume error: TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'TLSSocket'\n    |     property 'parser' -> object with constructor 'HTTPParser'\n    --- property 'socket' closes the circle\n    at JSON.stringify (<anonymous>)\n    at FreeNASSshDriver.findResourceByProperties (/home/csi/app/src/driver/freenas/ssh.js:174:18)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async FreeNASSshDriver.createShare (/home/csi/app/src/driver/freenas/ssh.js:643:37)\n    at async FreeNASSshDriver.CreateVolume (/home/csi/app/src/driver/controller-zfs/index.js:1213:22)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:217:18)",
    "service": "democratic-csi",
    "timestamp": "2023-04-15T00:55:33.227Z",
  }
```

the root of the issue is this:  i was in a hurry when i wrote the config yaml for the drivers, and stupidly put what i intended for `namePrefix` into `nameTemplate`, resulting in both shares being named the same and incomplete name.

so, i only ran into it because i'm dumb but it is a bit odd that the manifestation of this issue was a circular structure error!

**Comment by travisghansen** [comment]
I want to review this a little deeper before fully closing it out.

**Comment by disconn3ct** [comment]
Just as a datapoint, I hit it with zfs. (I suspect I made a similar mistake and it is a duplicate somewhere.)
