### ISSUE TITLE
k8s-csi-cleaner empty string error

### ISSUE THREAD

**Issue by valkenrath** [democratic-csi/democratic-csi#301]
K8s distro = Talos 1.4.x
TrueNAS distro = SCALE Bluefin (22.12.2-1)
Pod: democratic-csi/csi-driver
```
/home/csi/app# ./bin/k8s-csi-cleaner

101 k8s PVs discovered

Error: 13 INTERNAL: empty string
    at callErrorFromStatus (/home/csi/app/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/home/csi/app/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at Object.onReceiveStatus (/home/csi/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/home/csi/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/csi/app/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/home/csi/app/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/home/csi/app/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /home/csi/app/bin/k8s-csi-cleaner:71:37
    at new Promise (<anonymous>)
    at executeRPC (/home/csi/app/bin/k8s-csi-cleaner:70:10)
    at runControllerListVolumes (/home/csi/app/bin/k8s-csi-cleaner:90:10)
    at main (/home/csi/app/bin/k8s-csi-cleaner:120:17)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/csi/app/bin/k8s-csi-cleaner:172:7 {
  code: 13,
  details: 'empty string',
  metadata: Metadata {
    internalRepr: Map(3) {
      'content-type' => [Array],
      'date' => [Array],
      'content-length' => [Array]
    },
    options: {}
  }
}
```

Has been true for a while (many minor Talos/SCALE revisions), just been lazy with logging the fault. 

This is particularly painful when paired with the lack of an `onDelete` param for the storageClass; many dangling child datasets, no programmatic way to clean them up.

Happy to provide more info/logs, please advise!

**Comment by travisghansen** [comment]
https://github.com/democratic-csi/democratic-csi/issues/289

Can you `ls -l /csi-data/` inside that container?

**Comment by travisghansen** [comment]
Do any interesting logs show up from the respective `csi-driver` container of that pod?

**Comment by travisghansen** [comment]
Can you turn on debug logging? It will show the the actual request/response from the TrueNAS API.

**Comment by travisghansen** [comment]
This is an example response from CI:

```
{
  "id": "tank/ci/ce25fabf/v",
  "type": "FILESYSTEM",
  "name": "tank/ci/ce25fabf/v",
  "pool": "tank",
  "encrypted": false,
  "encryption_***": null,
  "key_loaded": false,
  "children": [],
...
```

If you search `ListVolume` here: https://github.com/democratic-csi/democratic-csi/actions/runs/6645915657/job/18061660688 you can see what the request/response should look like. The codepath is programmed relatively defensively so it's checking for a response code of `200` before hand. The combination of a `200` response code and an invalid value for `.children` seems quite odd.

**Comment by travisghansen** [comment]
hmm, I don't see that error in the output. Can you recreate the error and send over the respective logs?

**Comment by travisghansen** [comment]
We need to turn on debug logging so you see the raw requests/responses :( this issue seems really odd. I can add a small snippet of code to maybe try and catch it with more robust detail.

**Comment by travisghansen** [comment]
Well that response seems to have completed successfully. Can you run those logs out further to the point where the cleaner breaks?

**Comment by travisghansen** [comment]
Make sure to run the cleaner from the controller pod if that's not clear.

**Comment by travisghansen** [comment]
No. I looked through the previous logs sent and still cannot find a response where the children attribute is not present. Crazy stuff. If you actually did the clean operation with the ssh config have you tried going back to the api config and testing if it still blows up?

**Comment by travisghansen** [comment]
There are no downsides if you don't mind allowing ssh access to the node. I would like to discover the issue. The last set of logs you sent do not include a respective `ListVolumes` calls. Can you run the tool again against the api configuration and look for the `ListVolumes` request coming through along with the http debug immediately following it?

**Comment by travisghansen** [comment]
Can you also send over your full config (cleansed of secrets of course)?
