### ISSUE TITLE
TrueNAS CORE 13.0 NFS controller failing on http content-type header

### ISSUE THREAD

**Issue by shiddy** [democratic-csi/democratic-csi#308]
I am never able to run the controller pod without the following http error:
```
I0717 16:40:39.078506       1 feature_gate.go:245] feature gates: &{map[]}
I0717 16:40:39.078763       1 csi-provisioner.go:139] Version: v3.1.0
I0717 16:40:39.078789       1 csi-provisioner.go:162] Building kube configs for running in cluster...
I0717 16:40:39.081207       1 connection.go:154] Connecting to unix:///csi-data/csi.sock
I0717 16:40:39.088495       1 common.go:111] Probing CSI driver for readiness
I0717 16:40:39.088718       1 connection.go:183] GRPC call: /csi.v1.Identity/Probe
I0717 16:40:39.088748       1 connection.go:184] GRPC request: {}
I0717 16:40:42.404623       1 connection.go:186] GRPC response: {}
I0717 16:40:42.404978       1 connection.go:187] GRPC error: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
E0717 16:40:42.405271       1 csi-provisioner.go:197] CSI driver probe failed: rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
```

I've tried running this with the following stack:

TrueNas Core 13.0 (Up to date with all updates as of today)
10 Node cluster hosts running Ubuntu 22.04 LTE
Helm (Chart included below)

I intend to run with NFS and ISCSI but have hit issue with NFS for the time being, I will attempt ISCSI if it helps debugging

Server Screenshots:
![image](https://github.com/democratic-csi/democratic-csi/assets/3847723/0fb93598-d861-4860-8f26-f0c5dd0c5f55)
![image](https://github.com/democratic-csi/democratic-csi/assets/3847723/b097ebb8-eb8a-4519-8f45-1f0f8318169e)
![image](https://github.com/democratic-csi/democratic-csi/assets/3847723/fdbb7cbf-86c4-47cd-a36c-8b91ba76cafd)

and here is my helm chart with the fun parts redacted:

```
csiDriver:
  name: "org.democratic-csi.nfs"

storageClasses:
- name: freenas-nfs-csi
  defaultClass: false
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  allowVolumeExpansion: true
  parameters:
    fsType: nfs

  mountOptions:
  - noatime
  - nfsvers=4
  secrets:
    provisioner-secret:
    controller-publish-secret:
    node-stage-secret:
    node-publish-secret:
    controller-expand-secret:

driver:
  logLevel: debug
  config:
    driver: freenas-nfs
    instance_id:
    httpConnection:
      protocol: http
      host: 192.168.1.13
      port: 80
      apiKey: REDACTED
      allowInsecure: true
      apiVersion: 2
    sshConnection:
      host: 192.168.1.13
      port: 22
      username: root
      privateKey: |
        -----BEGIN OPENSSH PRIVATE KEY-----
        REDACTED
        -----END OPENSSH PRIVATE KEY-----
    zfs:
      datasetParentName: pool1/k8s/nfs/vols
      detachedSnapshotsDatasetParentName: pool1/k8s/nfs/snaps
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      datasetPermissionsGroup: 0
    nfs:
      shareHost: 192.168.1.13
      shareAlldirs: false
      shareAllowedHosts: []
      shareAllowedNetworks: []
      shareMaprootUser: root
      shareMaprootGroup: wheel
      shareMapallUser: ""
      shareMapallGroup: ""
```

I've tried changing the following:

* API access rather than username/password ( I have 2FA and assume that wouldn't help, though while I am testing I disabled it all together )
* Migrated from a non-root user to using the root account
  * I did make sure that the created user is in the sudoers file with nopasswd and tested that it works as expected. I also did make sure the helm chart had the use sudoEnabled

**Comment by travisghansen** [comment]
Welcome! Let's start with this..

https://github.com/democratic-csi/democratic-csi/issues/306

**Comment by shiddy** [comment]
Followed the recommendations in that issue, fwiw I have the debug flag in driver/config and loeken has it under driver/

for those playing the home game in the future, here is what I did

`kubectl logs zfs-nfs-democratic-csi-controller-podnamehere -c csi-driver -n democratic-csi`

I don't appear to be receiving any errors on that container
```
grpc implementation: @grpc/grpc-js
{"host":"zfs-nfs-democratic-csi-controller-7c65c6b69-7n8kj","level":"info","message":"initializing csi driver: freenas-nfs","service":"democratic-csi","timestamp":"2023-07-17T16:58:19.446Z"}
{"host":"zfs-nfs-democratic-csi-controller-7c65c6b69-7n8kj","level":"info","message":"starting csi server - node version: v16.18.0, package version: 1.8.3, config file: /config/..2023_07_17_16_57_27.524889483/driver-config-file.yaml, csi-name: org.democratic-csi.nfs, csi-driver: freenas-nfs, csi-mode: controller, csi-version: 1.5.0, address: , socket: unix:///csi-data/csi.sock.internal","service":"democratic-csi","timestamp":"2023-07-17T16:58:21.525Z"}
``` 

The rest of the containers don't appear to be throwing any obvious errors other than the "csi-proxy" container with the following:

```
2023/07/17 17:28:49 request (://localhost) POST /csi.v1.Identity/GetPluginInfo HTTP/2.0
2023/07/17 17:28:49 request headers map[Content-Type:[application/grpc] Grpc-Timeout:[89995498u] Te:[trailers] User-Agent:[grpc-go/1.40.0]]
2023/07/17 17:28:49 Dialing upstream: unix:///csi-data/csi.sock.internal
2023/07/17 17:28:49 http: proxy error: dial unix /csi-data/csi.sock.internal: connect: no such file or directory
```

**Comment by travisghansen** [comment]
Hmm is the proxy container continuously spewing that or only the very beginning and then looks better?

**Comment by shiddy** [comment]
spewing, but nothing different in each log other than the timeout identifier in brackets

**Comment by travisghansen** [comment]
So that container has a shared empty dir with the others where the sockets are shared. Can you exec into the csi-driver container and ls that dir to see what’s in there?

**Comment by shiddy** [comment]
forgive me for my ignorance, it took a lot of restarts but I was able to exec into the container and it does appear that /csi-data exists and has the sockets created, but only for a couple of seconds before the container crashes

```
$ kubectl exec --stdin --tty zfs-nfs-democratic-csi-controller-7c65c6b69-f7w9h -c csi-driver -n democratic-csi -- /bin/bash
error: unable to upgrade connection: container not found ("csi-driver")
$ kubectl exec --stdin --tty zfs-nfs-democratic-csi-controller-7c65c6b69-f7w9h -c csi-driver -n democratic-csi -- /bin/bash
root@zfs-nfs-democratic-csi-controller-7c65c6b69-f7w9h:/home/csi/app# ls /
bin  boot  config  csi-data  dev  etc  home  lib  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var
root@zfs-nfs-democratic-csi-controller-7c65c6b69-f7w9h:/home/csi/app# ls /csi-data/
csi.sock  csi.sock.internal
root@zfs-nfs-democratic-csi-controller-7c65c6b69-f7w9h:/home/csi/app# command terminated with exit code 137
```

**Comment by shiddy** [comment]
kubeadm w/ containerd://1.6.21 on bare metal

**Comment by travisghansen** [comment]
Something strange going on. What have you set as the resource limits? 137 often means it’s getting oom’d.

**Comment by shiddy** [comment]
basically the same story on every node

```
k8s1:~$ prlimit
RESOURCE   DESCRIPTION                              SOFT       HARD UNITS
AS         address space limit                 unlimited  unlimited bytes
CORE       max core file size                          0  unlimited bytes
CPU        CPU time                            unlimited  unlimited seconds
DATA       max data size                       unlimited  unlimited bytes
FSIZE      max file size                       unlimited  unlimited bytes
LOCKS      max number of file locks held       unlimited  unlimited locks
MEMLOCK    max locked-in-memory address space 1023418368 1023418368 bytes
MSGQUEUE   max bytes in POSIX mqueues             819200     819200 bytes
NICE       max nice prio allowed to raise              0          0
NOFILE     max number of open files                 1024    1048576 files
NPROC      max number of processes                 30793      30793 processes
RSS        max resident set size               unlimited  unlimited bytes
RTPRIO     max real-time priority                      0          0
RTTIME     timeout for real-time tasks         unlimited  unlimited microsecs
SIGPENDING max number of pending signals           30793      30793 signals
STACK      max stack size                        8388608  unlimited bytes
```

Memory seems to be mostly free as well

```
k8s1:~$ free -h
               total        used        free      shared  buff/cache   available
Mem:           7.6Gi       903Mi       5.1Gi       4.0Mi       1.7Gi       6.5Gi
Swap:             0B          0B          0B
```

**Comment by travisghansen** [comment]
I mean on the controller deployment/pod.

**Comment by shiddy** [comment]
I'm having a hard time keeping the containers up long enough to exec to them with those commands, they seem to hit the crashloop rather quickly

here is the details on that pod to hopefully show that there are not extra limits placed on those containers

```
Name:             zfs-nfs-democratic-csi-controller-7c65c6b69-pfqtb
Namespace:        democratic-csi
Priority:         0
Service Account:  zfs-nfs-democratic-csi-controller-sa
Node:             rpik8s8/192.168.69.8
Start Time:       Mon, 17 Jul 2023 13:17:28 -0600
Labels:           app.kubernetes.io/component=controller-linux
                  app.kubernetes.io/csi-role=controller
                  app.kubernetes.io/instance=zfs-nfs
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=democratic-csi
                  pod-template-hash=7c65c6b69
Annotations:      checksum/configmap: 5ce805bbcd6d5d6fcc219ae1115dd983378bcb0cf779e05459f79d91ed004438
                  checksum/secret: fab28d419876bcd4c8802718978ffab10ece8a094c4dc1c09f5b3056a1fc9a48
                  cni.projectcalico.org/containerID: 9739a34699008316f2d37b6bf996f67c9532852fd178283b5678af28807a095d
                  cni.projectcalico.org/podIP: 172.16.48.131/32
                  cni.projectcalico.org/podIPs: 172.16.48.131/32
Status:           Running
IP:               172.16.48.131
IPs:
  IP:           172.16.48.131
Controlled By:  ReplicaSet/zfs-nfs-democratic-csi-controller-7c65c6b69
Containers:
  external-provisioner:
    Container ID:  containerd://7465bac1225b85230b8231b7d516f12076cbceb14816780afbda862576075a99
    Image:         registry.k8s.io/sig-storage/csi-provisioner:v3.1.0
    Image ID:      registry.k8s.io/sig-storage/csi-provisioner@sha256:122bfb8c1edabb3c0edd63f06523e6940d958d19b3957dc7b1d6f81e9f1f6119
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=democratic-csi
      --timeout=90s
      --worker-threads=10
      --extra-create-metadata
      --csi-address=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 17 Jul 2023 13:38:33 -0600
      Finished:     Mon, 17 Jul 2023 13:38:34 -0600
    Ready:          False
    Restart Count:  9
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      NAMESPACE:  democratic-csi (v1:metadata.namespace)
      POD_NAME:   zfs-nfs-democratic-csi-controller-7c65c6b69-pfqtb (v1:metadata.name)
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qgbl (ro)
  external-resizer:
    Container ID:  containerd://8c338183413ffdf311f207f928c629ec43a2f8a73425ec513862fb6b6d9123f0
    Image:         registry.k8s.io/sig-storage/csi-resizer:v1.4.0
    Image ID:      registry.k8s.io/sig-storage/csi-resizer@sha256:9ebbf9f023e7b41ccee3d52afe39a89e3ddacdbb69269d583abfc25847cfd9e4
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=democratic-csi
      --timeout=90s
      --workers=10
      --csi-address=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    255
      Started:      Mon, 17 Jul 2023 13:38:34 -0600
      Finished:     Mon, 17 Jul 2023 13:38:34 -0600
    Ready:          False
    Restart Count:  9
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      NAMESPACE:  democratic-csi (v1:metadata.namespace)
      POD_NAME:   zfs-nfs-democratic-csi-controller-7c65c6b69-pfqtb (v1:metadata.name)
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qgbl (ro)
  external-snapshotter:
    Container ID:  containerd://767fa09d741cbc7808efd4b5f8b5f2a4b50c70a56f9bbcd63fab8e3165ccf4b2
    Image:         registry.k8s.io/sig-storage/csi-snapshotter:v5.0.1
    Image ID:      registry.k8s.io/sig-storage/csi-snapshotter@sha256:89e900a160a986a1a7a4eba7f5259e510398fa87ca9b8a729e7dec59e04c7709
    Port:          <none>
    Host Port:     <none>
    Args:
      --v=5
      --leader-election
      --leader-election-namespace=democratic-csi
      --timeout=90s
      --worker-threads=10
      --csi-address=/csi-data/csi.sock
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 17 Jul 2023 13:38:34 -0600
      Finished:     Mon, 17 Jul 2023 13:38:34 -0600
    Ready:          False
    Restart Count:  9
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      NAMESPACE:  democratic-csi (v1:metadata.namespace)
      POD_NAME:   zfs-nfs-democratic-csi-controller-7c65c6b69-pfqtb (v1:metadata.name)
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qgbl (ro)
  csi-driver:
    Container ID:  containerd://abe2bb2c3701e4fb3fdd61849ec30aa2bc72bc433122fb194216bfc1223d0bfc
    Image:         docker.io/democraticcsi/democratic-csi:latest
    Image ID:      docker.io/democraticcsi/democratic-csi@sha256:57eb874d0619987b67c6c0a1a04a644479a1a72a3bc717a318ed6f53a26266fe
    Port:          <none>
    Host Port:     <none>
    Args:
      --csi-version=1.5.0
      --csi-name=org.democratic-csi.nfs
      --driver-config-file=/config/driver-config-file.yaml
      --log-level=info
      --csi-mode=controller
      --server-socket=/csi-data/csi.sock.internal
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 17 Jul 2023 13:37:34 -0600
      Finished:     Mon, 17 Jul 2023 13:38:33 -0600
    Ready:          False
    Restart Count:  9
    Liveness:       exec [bin/liveness-probe --csi-version=1.5.0 --csi-address=/csi-data/csi.sock.internal] delay=10s timeout=15s period=60s #success=1 #failure=3
    Environment:
      NODE_EXTRA_CA_CERTS:  /tmp/certs/extra-ca-certs.crt
    Mounts:
      /config from config (rw)
      /csi-data from socket-dir (rw)
      /tmp/certs from extra-ca-certs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qgbl (ro)
  csi-proxy:
    Container ID:   containerd://99ceda25f760a6b17abe8d41c1c375fefbfd44b2ca4f13c0a46d697e38cfaed2
    Image:          docker.io/democraticcsi/csi-grpc-proxy:v0.5.3
    Image ID:       docker.io/democraticcsi/csi-grpc-proxy@sha256:4d65ca1cf17d941a8df668b8fe2f1c0cfa512c8b0dbef3ff89a4cd405e076923
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Mon, 17 Jul 2023 13:17:33 -0600
    Ready:          True
    Restart Count:  0
    Environment:
      BIND_TO:   unix:///csi-data/csi.sock
      PROXY_TO:  unix:///csi-data/csi.sock.internal
    Mounts:
      /csi-data from socket-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-5qgbl (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  socket-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  config:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zfs-nfs-democratic-csi-driver-config
    Optional:    false
  extra-ca-certs:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      zfs-nfs-democratic-csi
    Optional:  false
  kube-api-access-5qgbl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  25m                   default-scheduler  Successfully assigned democratic-csi/zfs-nfs-democratic-csi-controller-7c65c6b69-pfqtb to rpik8s8
  Normal   Pulled     25m                   kubelet            Container image "registry.k8s.io/sig-storage/csi-snapshotter:v5.0.1" already present on machine
  Normal   Created    25m                   kubelet            Created container external-snapshotter
  Normal   Started    25m                   kubelet            Started container external-snapshotter
  Normal   Pulled     25m                   kubelet            Container image "docker.io/democraticcsi/csi-grpc-proxy:v0.5.3" already present on machine
  Normal   Pulled     25m                   kubelet            Successfully pulled image "docker.io/democraticcsi/democratic-csi:latest" in 1.096368643s (1.096397254s including waiting)
  Normal   Started    25m                   kubelet            Started container csi-driver
  Normal   Started    25m                   kubelet            Started container csi-proxy
  Normal   Created    25m                   kubelet            Created container csi-proxy
  Normal   Pulled     24m (x2 over 25m)     kubelet            Container image "registry.k8s.io/sig-storage/csi-resizer:v1.4.0" already present on machine
  Normal   Started    24m (x2 over 25m)     kubelet            Started container external-provisioner
  Normal   Created    24m (x2 over 25m)     kubelet            Created container external-provisioner
  Normal   Pulled     24m (x2 over 25m)     kubelet            Container image "registry.k8s.io/sig-storage/csi-provisioner:v3.1.0" already present on machine
  Normal   Created    24m (x2 over 25m)     kubelet            Created container external-resizer
  Normal   Pulling    24m (x2 over 25m)     kubelet            Pulling image "docker.io/democraticcsi/democratic-csi:latest"
  Normal   Started    24m (x2 over 25m)     kubelet            Started container external-resizer
  Normal   Created    24m (x2 over 25m)     kubelet            Created container csi-driver
  Normal   Pulled     24m                   kubelet            Successfully pulled image "docker.io/democraticcsi/democratic-csi:latest" in 587.75939ms (587.780315ms including waiting)
  Warning  BackOff    9m51s (x88 over 24m)  kubelet            Back-off restarting failed container external-provisioner in pod zfs-nfs-democratic-csi-controller-7c65c6b69-pfqtb_democratic-csi(d1498d3b-9146-465c-a5d6-86a74c22450b)
  Warning  Unhealthy  5m (x5 over 22m)      kubelet            Liveness probe failed: grpc implementation: @grpc/grpc-js
```

**Comment by travisghansen** [comment]
Do you get any more logs from the csi-driver container before it dies?

**Comment by shiddy** [comment]
Hey, I asked a friend to look over my setup, and he smacked me upside the head and asked to check what kernel extensions were loaded on my nodes. Turns out that I didn't have cgroups enabled. somehow this was the first k8s pod that did resource allocation

I updated my /boot/firmware/cmdline.txt to the following:
`dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc quiet splash cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1`

after doing so I found the following logs from the csi-driver

```
$ kubectl logs zfs-nfs-democratic-csi-controller-cc4889f59-m7r9b -n democratic-csi -c csi-driver
grpc implementation: @grpc/grpc-js
{"host":"zfs-nfs-democratic-csi-controller-cc4889f59-m7r9b","level":"info","message":"initializing csi driver: freenas-nfs","service":"democratic-csi","timestamp":"2023-07-17T20:20:19.439Z"}
{"host":"zfs-nfs-democratic-csi-controller-cc4889f59-m7r9b","level":"info","message":"starting csi server - node version: v16.18.0, package version: 1.8.3, config file: /config/..2023_07_17_20_19_31
.1475505710/driver-config-file.yaml, csi-name: org.democratic-csi.nfs, csi-driver: freenas-nfs, csi-mode: controller, csi-version: 1.5.0, address: , socket: unix:///csi-data/csi.sock.internal","serv
ice":"democratic-csi","timestamp":"2023-07-17T20:20:21.320Z"}
{"host":"zfs-nfs-democratic-csi-controller-cc4889f59-m7r9b","level":"info","message":"new request - driver: FreeNASSshDriver method: Probe call: {\"metadata\":{\"user-agent\":[\"grpc-go/1.40.0\"],\"
x-forwarded-host\":[\"localhost\"]},\"request\":{},\"cancelled\":false}","service":"democratic-csi","timestamp":"2023-07-17T20:20:31.543Z"}
{"date":"Mon Jul 17 2023 20:20:31 GMT+0000 (Coordinated Universal Time)","error":{"level":"client-authentication"},"exception":true,"host":"zfs-nfs-democratic-csi-controller-cc4889f59-m7r9b","level"
:"error","message":"uncaughtException: All configured authentication methods failed\nError: All configured authentication methods failed\n    at doNextAuth (/home/csi/app/node_modules/ssh2/lib/clien
t.js:803:21)\n    at tryNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:993:7)\n    at USERAUTH_FAILURE (/home/csi/app/node_modules/ssh2/lib/client.js:373:11)\n    at 51 (/home/csi/app/node_
modules/ssh2/lib/protocol/handlers.misc.js:337:16)\n    at Protocol.onPayload (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:2025:10)\n    at AESGCMDecipherNative.decrypt (/home/csi/app/n
ode_modules/ssh2/lib/protocol/crypto.js:987:26)\n    at Protocol.parsePacket [as _parse] (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:1994:25)\n    at Protocol.parse (/home/csi/app/node
_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/home/csi/app/node_modules/ssh2/lib/client.js:713:21)\n    at Socket.emit (node:events:513:28)","os":{"loadavg":[0.73,0.45,
0.39],"uptime":4075.4},"process":{"argv":["/usr/local/bin/node","/home/csi/app/bin/democratic-csi","--csi-version=1.5.0","--csi-name=org.democratic-csi.nfs","--driver-config-file=/config/driver-conf
ig-file.yaml","--log-level=info","--csi-mode=controller","--server-socket=/csi-data/csi.sock.internal"],"cwd":"/home/csi/app","execPath":"/usr/local/bin/node","gid":0,"memoryUsage":{"arrayBuffers":1
25044,"external":26554091,"heapTotal":36655104,"heapUsed":32441816,"rss":89939968},"pid":1,"uid":0,"version":"v16.18.0"},"service":"democratic-csi","stack":"Error: All configured authentication meth
ods failed\n    at doNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:803:21)\n    at tryNextAuth (/home/csi/app/node_modules/ssh2/lib/client.js:993:7)\n    at USERAUTH_FAILURE (/home/csi/app
/node_modules/ssh2/lib/client.js:373:11)\n    at 51 (/home/csi/app/node_modules/ssh2/lib/protocol/handlers.misc.js:337:16)\n    at Protocol.onPayload (/home/csi/app/node_modules/ssh2/lib/protocol/Pr
otocol.js:2025:10)\n    at AESGCMDecipherNative.decrypt (/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js:987:26)\n    at Protocol.parsePacket [as _parse] (/home/csi/app/node_modules/ssh2/lib/
protocol/Protocol.js:1994:25)\n    at Protocol.parse (/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js:293:16)\n    at Socket.<anonymous> (/home/csi/app/node_modules/ssh2/lib/client.js:713:2
1)\n    at Socket.emit (node:events:513:28)","timestamp":"2023-07-17T20:20:31.680Z","trace":[{"column":21,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":"doNextAuth","line":803,"m
ethod":null,"native":false},{"column":7,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":"tryNextAuth","line":993,"method":null,"native":false},{"column":11,"file":"/home/csi/app/no
de_modules/ssh2/lib/client.js","function":"USERAUTH_FAILURE","line":373,"method":null,"native":false},{"column":16,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/handlers.misc.js","function":"
51","line":337,"method":null,"native":false},{"column":10,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.onPayload","line":2025,"method":"onPayload","native":
false},{"column":26,"file":"/home/csi/app/node_modules/ssh2/lib/protocol/crypto.js","function":"AESGCMDecipherNative.decrypt","line":987,"method":"decrypt","native":false},{"column":25,"file":"/home
/csi/app/node_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.parsePacket [as _parse]","line":1994,"method":"parsePacket [as _parse]","native":false},{"column":16,"file":"/home/csi/app/n
ode_modules/ssh2/lib/protocol/Protocol.js","function":"Protocol.parse","line":293,"method":"parse","native":false},{"column":21,"file":"/home/csi/app/node_modules/ssh2/lib/client.js","function":null
,"line":713,"method":null,"native":false},{"column":28,"file":"node:events","function":"Socket.emit","line":513,"method":"emit","native":false}]}
```

So there was also an issue with the ssh key on the root account. If I recall correctly I just used the web-gui to make the keypair from the user account, but the error was much more obvious when I got to this point. Either way, I created a new key of type ecdsa-sha2-nistp256 and everything works now. `ssh-keygen -t ecdsa-sha2-nistp256


Turns out the out of memory makes sense, thanks for the help @travisghansen!

**Comment by travisghansen** [comment]
Great! Hope it works well for ya!

**Comment by yidaqiang** [comment]
Yes, I have the same error message.
I have two mistakes:
one is the ssh key use of rsa encryption , it is not secure and been disabled. I recommend using ed25519
```
ssh-keygen -t ed25519
```
 the other is stupid mistake, if you using `sshConnection.privateKey`, must add  public SSH key to root, but I forgot it.
Navigate to Accounts > Users > root and add the public SSH key. Also change the shell to bash.
![image](https://github.com/democratic-csi/democratic-csi/assets/18599857/e6e11da2-70ee-4d86-a3b5-8eb38e403969)
