### ISSUE TITLE
CSI driver probe failed TypeError: err.getMessage is not a function

### ISSUE THREAD

**Issue by danielpanaite** [democratic-csi/democratic-csi#384]
Hi!
I am trying to rebuild my cluster and everything went smoothly until I tried to connect kubernetes to my truenas using the nfs csi. It worked on the previous cluster, each deployment was provisioning its persistent volume correctly.

This time when I try to install with the helm chart the pod fails to start with the error
```
Defaulted container "external-attacher" out of: external-attacher, external-provisioner, external-resizer, external-snapshotter, csi-driver, csi-proxy
I0402 16:46:59.186051       1 main.go:97] Version: v4.4.0
I0402 16:46:59.186897       1 connection.go:164] Connecting to unix:///csi-data/csi.sock
I0402 16:46:59.187607       1 common.go:138] Probing CSI driver for readiness
I0402 16:46:59.187619       1 connection.go:193] GRPC call: /csi.v1.Identity/Probe
I0402 16:46:59.187623       1 connection.go:194] GRPC request: {}
I0402 16:47:09.246258       1 connection.go:200] GRPC response: {}
I0402 16:47:09.246276       1 connection.go:201] GRPC error: rpc error: code = Internal desc = TypeError: err.getMessage is not a function TypeError: err.getMessage is not a function
    at FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2204:46)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
E0402 16:47:09.246305       1 main.go:142] CSI driver probe failed: rpc error: code = Internal desc = TypeError: err.getMessage is not a function TypeError: err.getMessage is not a function
    at FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2204:46)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
```

The csi-driver containers listst the same error
```
{"host":"zfs-nfs-democratic-csi-controller-85b9ffb4d6-26dzm","level":"error","message":"handler error - driver: FreeNASApiDriver method: Probe error: TypeError: err.getMessage is not a function TypeError: err.getMessage is not a function\n    at FreeNASApiDriver.Probe (/home/csi/app/src/driver/freenas/api.js:2204:46)\n    at runNextTicks (node:internal/process/task_queues:60:5)\n    at listOnTimeout (node:internal/timers:540:9)\n    at process.processTimers (node:internal/timers:514:7)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)","service":"democratic-csi","timestamp":"2024-04-02T17:13:30.103Z"}
```

The previous cluster no longer exists and is not using the volumes but from the Truenas dashboard all the pv appear as still attached to NFS. Could that be an issue? Though it is not working even if I try to specify a path to an empty dataset.

![image](https://github.com/democratic-csi/democratic-csi/assets/44780495/64e56931-3429-4fe5-8fa8-044faf644958)

**Comment by starcraft66** [comment]
I am experiencing the same issue randomly on some democratic csi node pods, but not all of them.

**Comment by travisghansen** [comment]
Should be fixed here: https://github.com/democratic-csi/democratic-csi/commit/38bee217dd4806b27e62ecb3fc4d335e004a9052

Give `v1.9.1` a try.
