### ISSUE TITLE
[freenas-api-nfs] volume expansion failes with 405 ??? 

### ISSUE THREAD

**Issue by markussiebert** [democratic-csi/democratic-csi#394]
Hi,

I tried to expand a nfs volume -  but it fails with:

```bash
external-resizer I0505 16:40:23.658274       1 connection.go:200] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Ty
pe":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":4}}},{"Type":{"Rpc":{"type":5}}},{"Type":{"Rpc":{"type":6}}},{"Type":{"Rpc":{"type"
:7}}},{"Type":{"Rpc":{"type":9}}},{"Type":{"Rpc":{"type":12}}},{"Type":{"Rpc":{"type":13}}}]}                                     
external-resizer I0505 16:40:23.658301       1 connection.go:201] GRPC error: <nil>                                               
external-resizer I0505 16:40:23.658335       1 connection.go:193] GRPC call: /csi.v1.Controller/ControllerExpandVolume            
external-resizer I0505 16:40:23.658343       1 connection.go:194] GRPC request: {"capacity_range":{"required_bytes":25769803776},"
volume_capability":{"AccessType":{"Mount":{"fs_type":"nfs","mount_flags":["noatime","nfsvers=4"]}},"access_mode":{"mode":7}},"volu
me_id":"pvc-f9456e89-d5c9-43ca-816b-4d4b9a45fc30"}                                                                                
csi-driver {"host":"democratic-csi-controller-9d657965b-8rmgd","level":"info","message":"new request - driver: FreeNASApiDriver me
thod: ControllerExpandVolume call: {\"path\":\"/csi.v1.Controller/ControllerExpandVolume\",\"metadata\":{},\"request\":{\"secrets\
":\"redacted\",\"volume_id\":\"pvc-f9456e89-d5c9-43ca-816b-4d4b9a45fc30\",\"capacity_range\":{\"required_bytes\":\"25769803776\",\
"limit_bytes\":\"0\"},\"volume_capability\":{\"access_mode\":{\"mode\":\"SINGLE_NODE_MULTI_WRITER\"},\"mount\":{\"mount_flags\":[\
"noatime\",\"nfsvers=4\"],\"fs_type\":\"nfs\",\"volume_mount_group\":\"\"},\"access_type\":\"mount\"}},\"pendingStatus\":{\"code\"
:0,\"details\":\"OK\"},\"cancelled\":false,\"trailingMetadata\":{}}","service":"democratic-csi","timestamp":"2024-05-05T16:40:23.6
59Z"}                                                                                                                             
csi-driver {"host":"democratic-csi-controller-9d657965b-8rmgd","level":"error","message":"handler error - driver: FreeNASApiDriver
 method: ControllerExpandVolume error: Error: \"<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><
h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\" Error: \"<html>\\r\\n<head><tit
le>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n
</body>\\r\\n</html>\\r\\n\"\n    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)\n    at process.processT
icksAndRejections (node:internal/process/task_queues:95:5)\n    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/sr
c/driver/freenas/api.js:3238:7)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)","service":"democratic
-csi","timestamp":"2024-05-05T16:40:23.668Z"}                                                                                     
external-resizer I0505 16:40:23.669561       1 connection.go:200] GRPC response: {}                                               
external-resizer I0505 16:40:23.669587       1 connection.go:201] GRPC error: rpc error: code = Internal desc = Error: "<html>\r\n
<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r
\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</
h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"                 
```

My fault or a bug?

**Comment by Malet** [comment]
I'm also getting the same issue with the `freenas-api-iscsi` driver:

```
Labels:        app.kubernetes.io/instance=opensearch                                                                                                                            
               app.kubernetes.io/name=opensearch                                                                                                                                
Annotations:   pv.kubernetes.io/bind-completed: yes                                                                                                                             
               pv.kubernetes.io/bound-by-controller: yes                                                                                                                        
               volume.beta.kubernetes.io/storage-provisioner: freenas-api-iscsi                                                                                                 
               volume.kubernetes.io/storage-provisioner: freenas-api-iscsi                                                                                                      
Finalizers:    [kubernetes.io/pvc-protection]                                                                                                                                   
Capacity:      50Gi                                                                                                                                                             
Access Modes:  RWO                                                                                                                                                              
VolumeMode:    Filesystem                                                                                                                                                       
Used By:       opensearch-cluster-master-0                                                                                                                                      
Conditions:                                                                                                                                                                     
  Type       Status  LastProbeTime                     LastTransitionTime                Reason  Message                                                                        
  ----       ------  -----------------                 ------------------                ------  -------                                                                        
  Resizing   True    Mon, 01 Jan 0001 00:00:00 +0000   Mon, 06 May 2024 12:40:19 +0100                                                                                          
Events:                                                                                                                                                                         
  Type     Reason              Age              From                                Message                                                                                     
  ----     ------              ----             ----                                -------                                                                                     
  Warning  ExternalExpanding   4s               volume_expand                       waiting for an external controller to expand this PVC                                       
  Normal   Resizing            2s (x2 over 3s)  external-resizer freenas-api-iscsi  External resizer is resizing volume pvc-940180dc-975c-43e9-a54e-f5c80ec1e1f0                
  Warning  VolumeResizeFailed  1s (x2 over 3s)  external-resizer freenas-api-iscsi  resize volume "pvc-940180dc-975c-43e9-a54e-f5c80ec1e1f0" by resizer "freenas-api-iscsi" fail
ed: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx<
/center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</c
enter>\r\n</body>\r\n</html>\r\n"                                                                                                                                               
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)                                                                                                     
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)                                                                                               
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)                                                                           
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)                                                                                                      
```

**Comment by dark0dave** [comment]
BUGARRRRRRuuuuu

**Comment by Malet** [comment]
```
csi-driver {"host":"truenas-iscsi-democratic-csi-controller-65ddb589b6-nlvqd","level":"debug","message":"FREENAS HTTP RESPONSE BODY: {\"id\":\"samsung/x/iscsi/pvc-940180dc-975c-43e9-a54e-f5c80ec1e1f0\",\"type\":\"VOLUME\",\"name\":\"samsung/x/iscsi/pvc-940180dc-975c-43e9-a54e-f5c80ec1e1f0\",\"pool\":\"samsung\",\"encrypted\":false,\"encryption_root\":null,\"key_load ...
csi-driver {"host":"truenas-iscsi-democratic-csi-controller-65ddb589b6-nlvqd","level":"info","message":"new response - driver: FreeNASApiDriver method: ControllerExpandVolume response: {\"capacity_bytes\":220117073920,\"node_expansion_required\":true}","service":"democratic-csi","timestamp":"2024-05-06T16:33:47.058Z"}                                                             
```
This seems to be working now debug logging is enabled :laughing:

**Comment by markussiebert** [comment]
crazy - the same at my installation - enabling debug logs leads to working resize and volumes that get status released...

**Comment by f1reSong** [comment]
+1, it's working on logLevel debug

**Comment by markussiebert** [comment]
But still would consider this a bug XD

**Comment by djjudas21** [comment]
I'm wondering if it's not the enabling of debug logging that fixes the problem, but the pod restart required to enable it. 

Anyhow, I've run into the same problem with the TrueNAS NFS driver and fortunately I already had debug logging enabled for a different bug, so hopefully I've captured something useful. In my case, the PVC is `media/videos` and the PV is `pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a`. The request was made by hand, editing the PVC definition to increase the size from 1Ti to 2Ti.

## external-resizer
```
I0714 17:50:55.652455       1 controller.go:295] Started PVC processing "media/videos"
I0714 17:50:55.676971       1 connection.go:193] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0714 17:50:55.677011       1 connection.go:194] GRPC request: {}
I0714 17:50:55.677125       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"media", Name:"videos", UID:"01eaeb19-5739-4c91-a04a-b2d724f0b61a", APIVersion:"v1", ResourceVersion:"219711498", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a
I0714 17:50:55.680990       1 connection.go:200] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":4}}},{"Type":{"Rpc":{"type":5}}},{"Type":{"Rpc":{"type":6}}},{"Type":{"Rpc":{"type":7}}},{"Type":{"Rpc":{"type":9}}},{"Type":{"Rpc":{"type":12}}},{"Type":{"Rpc":{"type":13}}}]}
I0714 17:50:55.681388       1 connection.go:201] GRPC error: <nil>
I0714 17:50:55.681690       1 connection.go:193] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0714 17:50:55.681922       1 connection.go:194] GRPC request: {"capacity_range":{"required_bytes":2199023255552},"volume_capability":{"AccessType":{"Mount":{"fs_type":"nfs"}},"access_mode":{"mode":5}},"volume_id":"pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a"}
I0714 17:50:55.691373       1 connection.go:200] GRPC response: {}
I0714 17:50:55.691404       1 connection.go:201] GRPC error: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
E0714 17:50:55.691497       1 controller.go:286] Error syncing PVC: resize volume "pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a" by resizer "org.democratic-csi.nfs" failed: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
I0714 17:50:55.691587       1 controller.go:295] Started PVC processing "media/videos"
I0714 17:50:55.691670       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"media", Name:"videos", UID:"01eaeb19-5739-4c91-a04a-b2d724f0b61a", APIVersion:"v1", ResourceVersion:"219711498", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a" by resizer "org.democratic-csi.nfs" failed: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
I0714 17:50:55.699405       1 connection.go:193] GRPC call: /csi.v1.Controller/ControllerGetCapabilities
I0714 17:50:55.699565       1 connection.go:194] GRPC request: {}
I0714 17:50:55.699835       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"media", Name:"videos", UID:"01eaeb19-5739-4c91-a04a-b2d724f0b61a", APIVersion:"v1", ResourceVersion:"219711498", FieldPath:""}): type: 'Normal' reason: 'Resizing' External resizer is resizing volume pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a
I0714 17:50:55.703136       1 connection.go:200] GRPC response: {"capabilities":[{"Type":{"Rpc":{"type":1}}},{"Type":{"Rpc":{"type":3}}},{"Type":{"Rpc":{"type":4}}},{"Type":{"Rpc":{"type":5}}},{"Type":{"Rpc":{"type":6}}},{"Type":{"Rpc":{"type":7}}},{"Type":{"Rpc":{"type":9}}},{"Type":{"Rpc":{"type":12}}},{"Type":{"Rpc":{"type":13}}}]}
I0714 17:50:55.703182       1 connection.go:201] GRPC error: <nil>
I0714 17:50:55.703220       1 connection.go:193] GRPC call: /csi.v1.Controller/ControllerExpandVolume
I0714 17:50:55.703233       1 connection.go:194] GRPC request: {"capacity_range":{"required_bytes":2199023255552},"volume_capability":{"AccessType":{"Mount":{"fs_type":"nfs"}},"access_mode":{"mode":5}},"volume_id":"pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a"}
I0714 17:50:55.711290       1 connection.go:200] GRPC response: {}
I0714 17:50:55.711331       1 connection.go:201] GRPC error: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
E0714 17:50:55.711648       1 controller.go:286] Error syncing PVC: resize volume "pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a" by resizer "org.democratic-csi.nfs" failed: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
I0714 17:50:55.712134       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"media", Name:"videos", UID:"01eaeb19-5739-4c91-a04a-b2d724f0b61a", APIVersion:"v1", ResourceVersion:"219711498", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-01eaeb19-5739-4c91-a04a-b2d724f0b61a" by resizer "org.democratic-csi.nfs" failed: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
```

## csi-driver

Had to attach this as a file as it's huge. Lots of repeated messages, but I've attached the whole log anyway. There's a suspicious amount of HTML in what should be API logs.

[csi-driver.log](https://github.com/user-attachments/files/16228294/csi-driver.log)

**Comment by mlipscombe** [comment]
> I'm wondering if it's not the enabling of debug logging that fixes the problem, but the pod restart required to enable it.

I think that's exactly what is going on.  The 405 errors seem to come about because democratic-csi is suddenly sending API version 1 requests.  I wonder if there is a race condition where, if when democratic-csi is determining whether the server supports the v2 API, something other than 200 is returned because TrueNAS is in a mood, which then pins the API version at 1.

**Comment by djjudas21** [comment]
Hey @travisghansen - any progress on this one? It's still occurring for me when I create volumes or snapshots.

I'm running with debug logging set like so:

```yaml
controller:
  enabled: true
  driver:
    enabled: true
    logLevel: debug
```

The `external-provisioner` log is full of errors like these:

```
I1024 20:17:39.358310       1 controller.go:1152] handleProtectionFinalizer Volume : &PersistentVolume{ObjectMeta:{pvc-610ea31c-aba9-4ade-8338-272503b565a8    3eb0ebe7-0ae2-4ba4-b4c8-1d60dbafd92f 279556082 0 2024-10-23 07:54:08 +0000 UTC <nil> <nil> map[] map[pv.kubernetes.io/provisioned-by:org.democratic-csi.nfs volume.kubernetes.io/provisioner-deletion-secret-name: volume.kubernetes.io/provisioner-deletion-secret-namespace:] [] [kubernetes.io/pv-protection] [{csi-provisioner Update v1 2024-10-23 07:54:08 +0000 UTC FieldsV1 {"f:metadata":{"f:annotations":{".":{},"f:pv.kubernetes.io/provisioned-by":{},"f:volume.kubernetes.io/provisioner-deletion-secret-name":{},"f:volume.kubernetes.io/provisioner-deletion-secret-namespace":{}}},"f:spec":{"f:accessModes":{},"f:capacity":{".":{},"f:storage":{}},"f:claimRef":{".":{},"f:apiVersion":{},"f:kind":{},"f:name":{},"f:namespace":{},"f:resourceVersion":{},"f:uid":{}},"f:csi":{".":{},"f:driver":{},"f:fsType":{},"f:volumeAttributes":{".":{},"f:node_attach_driver":{},"f:provisioner_driver":{},"f:provisioner_driver_instance_id":{},"f:server":{},"f:share":{},"f:storage.kubernetes.io/csiProvisionerIdentity":{}},"f:volumeHandle":{}},"f:persistentVolumeReclaimPolicy":{},"f:storageClassName":{},"f:volumeMode":{}}} } {kubelite Update v1 2024-10-23 07:54:16 +0000 UTC FieldsV1 {"f:status":{"f:phase":{}}} status}]},Spec:PersistentVolumeSpec{Capacity:ResourceList{storage: {{1073741824 0} {<nil>} 1Gi BinarySI},},PersistentVolumeSource:PersistentVolumeSource{GCEPersistentDisk:nil,AWSElasticBlockStore:nil,HostPath:nil,Glusterfs:nil,NFS:nil,RBD:nil,ISCSI:nil,Cinder:nil,CephFS:nil,FC:nil,Flocker:nil,FlexVolume:nil,AzureFile:nil,VsphereVolume:nil,Quobyte:nil,AzureDisk:nil,PhotonPersistentDisk:nil,PortworxVolume:nil,ScaleIO:nil,Local:nil,StorageOS:nil,CSI:&CSIPersistentVolumeSource{Driver:org.democratic-csi.nfs,VolumeHandle:pvc-610ea31c-aba9-4ade-8338-272503b565a8,ReadOnly:false,FSType:nfs,VolumeAttributes:map[string]string{node_attach_driver: nfs,provisioner_driver: freenas-api-nfs,provisioner_driver_instance_id: truenas,server: 192.168.0.2,share: /mnt/ssd/k8s/vols/pvc-610ea31c-aba9-4ade-8338-272503b565a8,storage.kubernetes.io/csiProvisionerIdentity: 1729089971111-9495-org.democratic-csi.nfs,},ControllerPublishSecretRef:nil,NodeStageSecretRef:nil,NodePublishSecretRef:nil,ControllerExpandSecretRef:nil,NodeExpandSecretRef:nil,},},AccessModes:[ReadWriteOnce],ClaimRef:&ObjectReference{Kind:PersistentVolumeClaim,Namespace:velero,Name:bookstack-20241023075348-5cbg6,UID:610ea31c-aba9-4ade-8338-272503b565a8,APIVersion:v1,ResourceVersion:279555879,FieldPath:,},PersistentVolumeReclaimPolicy:Delete,StorageClassName:truenas,MountOptions:[],VolumeMode:*Filesystem,NodeAffinity:nil,},Status:PersistentVolumeStatus{Phase:Released,Message:,Reason:,LastPhaseTransitionTime:2024-10-23 07:54:16 +0000 UTC,},}
I1024 20:17:39.358466       1 controller.go:1239] shouldDelete volume "pvc-610ea31c-aba9-4ade-8338-272503b565a8"
I1024 20:17:39.358477       1 controller.go:1269] shouldDelete volume "pvc-610ea31c-aba9-4ade-8338-272503b565a8" is true
I1024 20:17:39.358485       1 controller.go:1113] shouldDelete Volume: "pvc-610ea31c-aba9-4ade-8338-272503b565a8"
I1024 20:17:39.358494       1 controller.go:1509] delete "pvc-610ea31c-aba9-4ade-8338-272503b565a8": started
I1024 20:17:39.358506       1 controller.go:1279] volume pvc-610ea31c-aba9-4ade-8338-272503b565a8 does not need any deletion secrets
I1024 20:17:39.358523       1 connection.go:193] GRPC call: /csi.v1.Controller/DeleteVolume
I1024 20:17:39.358534       1 connection.go:194] GRPC request: {"volume_id":"pvc-610ea31c-aba9-4ade-8338-272503b565a8"}
I1024 20:17:39.379176       1 connection.go:200] GRPC response: {}
I1024 20:17:39.379215       1 connection.go:201] GRPC error: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetDelete (/home/csi/app/src/driver/freenas/http/api.js:423:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/csi/app/src/driver/freenas/api.js:3102:11
    at async Object.retry (/home/csi/app/src/utils/general.js:217:14)
    at async FreeNASApiDriver.DeleteVolume (/home/csi/app/src/driver/freenas/api.js:3098:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
E1024 20:17:39.379256       1 controller.go:1519] delete "pvc-610ea31c-aba9-4ade-8338-272503b565a8": volume deletion failed: rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetDelete (/home/csi/app/src/driver/freenas/http/api.js:423:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/csi/app/src/driver/freenas/api.js:3102:11
    at async Object.retry (/home/csi/app/src/utils/general.js:217:14)
    at async FreeNASApiDriver.DeleteVolume (/home/csi/app/src/driver/freenas/api.js:3098:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
W1024 20:17:39.379316       1 controller.go:989] Retrying syncing volume "pvc-610ea31c-aba9-4ade-8338-272503b565a8", failure 540
E1024 20:17:39.379366       1 controller.go:1007] error syncing volume "pvc-610ea31c-aba9-4ade-8338-272503b565a8": rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetDelete (/home/csi/app/src/driver/freenas/http/api.js:423:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/csi/app/src/driver/freenas/api.js:3102:11
    at async Object.retry (/home/csi/app/src/utils/general.js:217:14)
    at async FreeNASApiDriver.DeleteVolume (/home/csi/app/src/driver/freenas/api.js:3098:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
I1024 20:17:39.379628       1 event.go:298] Event(v1.ObjectReference{Kind:"PersistentVolume", Namespace:"", Name:"pvc-610ea31c-aba9-4ade-8338-272503b565a8", UID:"3eb0ebe7-0ae2-4ba4-b4c8-1d60dbafd92f", APIVersion:"v1", ResourceVersion:"279556082", FieldPath:""}): type: 'Warning' reason: 'VolumeFailedDelete' rpc error: code = Internal desc = Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n" Error: "<html>\r\n<head><title>405 Not Allowed</title></head>\r\n<body>\r\n<center><h1>405 Not Allowed</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n"
    at Api.DatasetDelete (/home/csi/app/src/driver/freenas/http/api.js:423:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/csi/app/src/driver/freenas/api.js:3102:11
    at async Object.retry (/home/csi/app/src/utils/general.js:217:14)
    at async FreeNASApiDriver.DeleteVolume (/home/csi/app/src/driver/freenas/api.js:3098:7)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
I1024 20:17:39.833703       1 leaderelection.go:281] successfully renewed lease democratic-csi/org-democratic-csi-nfs
```

**Comment by ruifung** [comment]
I've just encountered this again and pulled this out of my logs (apologies for the format, I pulled it out of loki)

Of interest to note that the REQUEST DETAILS, seems to be sending volsize null?

```
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "debug",
  "message": "FREENAS HTTP REQUEST DETAILS: {\"headers\":{\"Accept\":\"application/json\",\"User-Agent\":\"democratic-csi-driver\",\"Content-Type\":\"application/json\",\"Authorization\":\"redacted\"},\"responseType\":\"json\",\"timeout\":60000,\"method\":\"PUT\",\"url\":\"https://redacted/api/v1.0/pool/dataset/id/hdd%2Fk8s-pw%2Fvol%2Fpvc-65af8dde-d8d4-4dbc-8d4d-8914310cd2ac/\",\"data\":{\"volsize\":null,\"user_properties_update\":[]}}",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "debug",
  "message": "FREENAS HTTP REQUEST DURATION: 0.01s",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "debug",
  "message": "FREENAS HTTP ERROR: null",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "debug",
  "message": "FREENAS HTTP RESPONSE STATUS CODE: 405",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "debug",
  "message": "FREENAS HTTP RESPONSE HEADERS: {\"server\":\"nginx\",\"date\":\"Fri, 13 Dec 2024 04:38:35 GMT\",\"content-type\":\"text/html\",\"content-length\":\"150\",\"connection\":\"keep-alive\",\"strict-transport-security\":\"max-age=0; includeSubDomains; preload\",\"x-content-type-options\":\"nosniff\",\"x-xss-protection\":\"1; mode=block\",\"permissions-policy\":\"geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()\",\"referrer-policy\":\"strict-origin\",\"x-frame-options\":\"SAMEORIGIN\"}",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "debug",
  "message": "FREENAS HTTP RESPONSE BODY: \"<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\"",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
{
  "host": "democratic-csi-okinawa-iscsi-controller-66478b5b4-nkwfv",
  "level": "error",
  "message": "handler error - driver: FreeNASApiDriver method: ControllerExpandVolume error: Error: \"<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\" Error: \"<html>\\r\\n<head><title>405 Not Allowed</title></head>\\r\\n<body>\\r\\n<center><h1>405 Not Allowed</h1></center>\\r\\n<hr><center>nginx</center>\\r\\n</body>\\r\\n</html>\\r\\n\"\n    at Api.DatasetSet (/home/csi/app/src/driver/freenas/http/api.js:443:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async FreeNASApiDriver.ControllerExpandVolume (/home/csi/app/src/driver/freenas/api.js:3238:7)\n    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)",
  "service": "democratic-csi",
  "timestamp": "2024-12-13T04:38:35.277Z"
}
```

**Comment by travisghansen** [comment]
Yeah, all of them are likely connected to the wrong api version being used. It sounds like the `REST` api is being deprecated so I will probably use that opportunity to remove the old v1 and v2 code and just require the latest scale using the websocket api.

**Comment by goldyfruit** [comment]
Just got the same behavior!
