### ISSUE TITLE
Sporadic ProvisioningFailed 

### ISSUE THREAD

**Issue by ddollar** [democratic-csi/democratic-csi#415]
I'm running democratic-csi via helm and on the 1.9.3 release

It seems like after a while something goes bad. All PVCs start generating events like the following when trying to create:

```
  Warning  ProvisioningFailed  42s (x6 over 70s)  org.democratic-csi.nfs_nas-nfs-democratic-csi-controller-7759965846-n6kkr_6f22f837-e5a4-405c-9792-9e1eee08ee47  failed to provision volume with StorageClass "nas-nfs": rpc error: code = Internal desc = TypeError: Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')
    at FreeNASSshDriver.createShare (/home/csi/app/src/driver/freenas/ssh.js:407:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASSshDriver.CreateVolume (/home/csi/app/src/driver/controller-zfs/index.js:1225:22)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
```

If I delete all of the pods in the democratic-csi namespace and let them be recreated everything will start working again for a while.

**Comment by travisghansen** [comment]
I’ll take a peek for the next release.

**Comment by TheAceMan** [comment]
I just ran into this as well. All existing PVC (nfs and iscsi) work fine. But a new PVC sits in a pending state with this warning.

```
Warning  ProvisioningFailed    25s (x13 over 19m)    org.democratic-csi.nfs_zfs-nfs-provisioner-democratic-csi-controller-55c554899c-z8bfz_f413a9af-2c5b-42b3-b5cf-01bf357e6b24  failed to provision volume with StorageClass "freenas-nfs-csi": rpc error: code = Internal desc = TypeError: Cannot read properties of undefined (reading 'includes') TypeError: Cannot read properties of undefined (reading 'includes')
    at FreeNASSshDriver.createShare (/home/csi/app/src/driver/freenas/ssh.js:407:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async FreeNASSshDriver.CreateVolume (/home/csi/app/src/driver/controller-zfs/index.js:1225:22)
    at async requestHandlerProxy (/home/csi/app/bin/democratic-csi:222:18)
```

I did not see any other errors in the provisioners, but let me know if there is anything else that would help.

**Comment by ddollar** [comment]
As a workaround I am killing all of the pods in the democratic-csi namespace once an hour and it seems to get me by.

**Comment by TheAceMan** [comment]
I left this in a broken state with the PVC pending to look into more later but it appears the PV was successfully created after a while on it's own.

PVC creation date: 2024-09-17T16:58:09Z
PV creation date, 26 hours later: 2024-09-18T20:53:40Z

I don't see any restarts of the nfs provisioner pods.

**Comment by travisghansen** [comment]
Does this problem persist?
