### ISSUE TITLE
SMB error on TrueNAS 24.10.2 - Option "stripacl" required to change permission

### ISSUE THREAD

**Issue by jengo** [democratic-csi/democratic-csi#440]
I am trying to setup SMB with my Kubernetes cluster.  However, when I try to provision a PVC I am getting the following error on the TrueNAS box.

```
[2024/12/24 13:16:24] (ERROR) middlewared.job.run():503 - Job <bound method accepts.<locals>.wrap.<locals>.nf of <middlewared.plugins.filesystem_.acl.FilesystemService object at 0x7f3cc70858d0>> failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 488, in run
    await self.future
  File "/usr/lib/python3/dist-packages/middlewared/job.py", line 535, in __run_body
    rv = await self.middleware.run_in_thread(self.method, *args)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1364, in run_in_thread
    return await self.run_in_executor(io_thread_pool_executor, method, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/main.py", line 1361, in run_in_executor
    return await loop.run_in_executor(pool, functools.partial(method, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 183, in nf
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/schema/processor.py", line 55, in nf
    res = f(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/middlewared/plugins/filesystem_/acl.py", line 269, in setperm
    verrors.check()
  File "/usr/lib/python3/dist-packages/middlewared/service_exception.py", line 72, in check
    raise self
middlewared.service_exception.ValidationErrors: [EINVAL] filesystem.setperm.mode: Non-trivial ACL present on [/mnt/nvmepool1/k8s/smb/v/pvc-14f4a431-9c37-421a-af33-e49794f388b0]. Option "stripacl" required to change permission
```

I've tried to quickly strip the ACL from the volume when it fails the first time.  But the volume never gets provisioned.  The PVC is always stuck at Pending.

Here is the current config I am using:

```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: truenas-smb-nvme-driver-config
  namespace: democratic-csi
stringData:
  driver-config-file.yaml: |-
    driver: freenas-api-smb
    httpConnection:
      allowInsecure: true
      host: [ redacted ]
      apiKey: [ redacted ]
      port: 443
      protocol: https
      username: root
      apiVersion: 2
    instance_id: null
    smb:
      shareHost: [ redacted ]
      nameTemplate: ""
      namePrefix: ""
      nameSuffix: ""
      shareAuxiliaryConfigurationTemplate: |
        #guest ok = yes
        #guest only = yes
      shareHome: false
      shareAllowedHosts: []
      shareDeniedHosts: []
      #shareDefaultPermissions: true
      shareGuestOk: true
      #shareGuestOnly: true
      #shareShowHiddenFiles: true
      shareRecycleBin: true
      shareBrowsable: false
      shareAccessBasedEnumeration: true
      shareTimeMachine: false
      #shareStorageTask:

    zfs:
      # total volume name (zvol/<datasetParentName>/<pvc name>) length cannot exceed 63 chars
      # https://www.ixsystems.com/documentation/freenas/11.2-U5/storage.html#zfs-zvol-config-opts-tab
      # standard volume naming overhead is 46 chars
      # datasetParentName should therefore be 17 chars or less
      datasetEnableQuotas: true
      datasetEnableReservation: false
      datasetParentName: nvmepool1/k8s/smb/v
      datasetPermissionsGroup: 0
      datasetPermissionsMode: "0777"
      datasetPermissionsUser: 0
      detachedSnapshotsDatasetParentName: nvmepool1/k8s/smb/s
```

I've also tried messing around these with several different settings and it doesn't have any affect.  Many times the settings cause the volume on the TrueNAS box to never actually get created.

```
  datasetProperties:
    aclmode: restricted
    casesensitivity: mixed
```

The controller logs don't show anything useful, just lease renewals.

**Comment by travisghansen** [comment]
Welcome! I am just getting around to testing with 24.10. It appears they have change the api behavior and so this needs reworked.

You should remove:

```
  datasetPermissionsMode:
  datasetPermissionsUser:
  datasetPermissionsGroup:
```

And then as necessary add the following (tailor to your acls):

```
  # SCALE
  #datasetPermissionsAclsBinary: nfs4xdr_setfacl

  #datasetPermissionsAcls:
  #  - "-m u:kube:full_set:allow"

```
