### ISSUE TITLE
Controller Containers Restarting Frequently

### ISSUE THREAD

**Issue by jodyt** [democratic-csi/democratic-csi#84]
Hello,

I'm running democratic-csi on a 3 node microk8s (raspberry pi) cluster.  I configured democratic-csi by following the nfs portion of the instructions in https://jonathangazeley.com/2021/01/05/using-truenas-to-provide-persistent-storage-for-kubernetes/.  I'm able to create/delete pvc's seemingly, but several containers (external-provisioner, external-resizer, external-snapshotter) in the controller pod are restarting frequently with errors like:

`I0509 20:40:54.335867       1 leaderelection.go:273] successfully renewed lease democratic-csi/org-democratic-csi-nfs-hdd-client
I0509 20:41:00.696557       1 leaderelection.go:273] successfully renewed lease democratic-csi/org-democratic-csi-nfs-hdd-client
E0509 20:41:15.700411       1 leaderelection.go:361] Failed to update lock: Put "https://10.152.183.1:443/apis/coordination.k8s.io/v1/namespaces/democratic-csi/leases/org-democratic-csi-nfs-hdd-client": context deadline exceeded
I0509 20:41:15.700610       1 leaderelection.go:278] failed to renew lease democratic-csi/org-democratic-csi-nfs-hdd-client: timed out waiting for the condition
F0509 20:41:15.700682       1 leader_election.go:209] stopped leading
goroutine 1 [running]:
k8s.io/klog/v2.stacks(0x400000e001, 0x4000174000, 0x46, 0x185)
	/workspace/vendor/k8s.io/klog/v2/klog.go:1026 +0xac
k8s.io/klog/v2.(*loggingT).output(0x1f801c0, 0x4000000003, 0x0, 0x0, 0x400025b110, 0x1ec110e, 0x12, 0xd1, 0x40005d5500)
	/workspace/vendor/k8s.io/klog/v2/klog.go:975 +0x168
k8s.io/klog/v2.(*loggingT).printDepth(0x1f801c0, 0x4000000003, 0x0, 0x0, 0x0, 0x0, 0x1, 0x40005e34a0, 0x1, 0x1)
	/workspace/vendor/k8s.io/klog/v2/klog.go:732 +0x120
k8s.io/klog/v2.(*loggingT).print(...)
	/workspace/vendor/k8s.io/klog/v2/klog.go:714
k8s.io/klog/v2.Fatal(...)
	/workspace/vendor/k8s.io/klog/v2/klog.go:1482
github.com/kubernetes-csi/csi-lib-utils/leaderelection.(*leaderElection).Run.func2()
	/workspace/vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go:209 +0xb4
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run.func1(0x4000517b00)
	/workspace/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:199 +0x2c
k8s.io/client-go/tools/leaderelection.(*LeaderElector).Run(0x4000517b00, 0x1507f80, 0x400013e000)
	/workspace/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:209 +0x130
k8s.io/client-go/tools/leaderelection.RunOrDie(0x1507fc0, 0x4000048018, 0x1512420, 0x4000249180, 0x37e11d600, 0x2540be400, 0x12a05f200, 0x400032bee0, 0x139c228, 0x139c230, ...)
	/workspace/vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go:222 +0x6c
github.com/kubernetes-csi/csi-lib-utils/leaderelection.(*leaderElection).Run(0x40004f35f0, 0x40004f35f0, 0x0)
	/workspace/vendor/github.com/kubernetes-csi/csi-lib-utils/leaderelection/leader_election.go:222 +0x428
main.main()
	/workspace/cmd/csi-provisioner/csi-provisioner.go:490 +0x2774`

Any suggestions?  Thanks!

**Comment by jodyt** [comment]
Thank you.  Disabling leader election did seem to address the restart issues.  Are there any "risks" from democratic-csi perspective from disabling it?  Does leader election serve any purpose when replicas is set to 1?
